<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Creating a Facebook-like Registration Form with jQuery</title>
<link rel="stylesheet" type="text/css" href="/chichi/public/css/demo.css" />
<script type="text/javascript" src="/chichi/public/js/jquery.js"></script>
<script type="text/javascript" src="/chichi/public/js/login.js" ></script>
<script type="text/javascript" src="/chichi/public/js/chichi.js" ></script>

<body>
<div  id="header">
	<div id="loginContainer">
                <a href="#" id="loginButton"><span>Login</span><em></em></a>
                <div style="clear:both"></div>
                <div id="loginBox">                
                    <form id="loginForm" action="/chichi/public/index/login" method="post">
                        <fieldset id="body">
                            <fieldset>
                                <label for="email">Email Address</label>
                                <input type="text" name="email" id="email" />
                            </fieldset>
                            <fieldset>
                                <label for="password">Password</label>
                                <input type="password" name="password" id="password" />
                            </fieldset>
                            <input type="submit" id="login" value="Sign in" />
                            <label for="checkbox"><input type="checkbox" id="checkbox" />Remember me</label>
                        </fieldset>
                        <span><a href="#">Forgot your password?</a></span>
                    </form>
                </div>
            </div>
</div>


<div id="div-regForm">
<div class="form-title">Sign Up</div>
<div class="form-sub-title">It's free and anyone can join</div>
<?php
if($this->messages){
		?>
		<div style="color: #CD0A0A;	font-size: 11px; border-radius: 5px; padding-left: 45px; padding-top: 10px; width: 85%;">
		<?php
	foreach($this->messages as $value){
		foreach($value as $val){
			echo $val;
			echo "<br />";
			echo "<br />";
		}
	}
	echo "</div>";
}
?>
<form id="regForm" action="/chichi/public/index/signup" enctype="multipart/form-data" method="post">
<table>
  <tbody>
  <tr>
    <td><label for="fname">First Name:</label></td>
    <td><div class="input-container"><input name="firstname" id="fname" type="text" /></div></td>
  </tr>
  <tr>
    <td><label for="lname">Last Name:</label></td>
    <td><div class="input-container"><input name="lastname" id="lname" type="text" /></div></td>
  </tr>
  <tr>
    <td><label for="email">Your Email:</label></td>
    <td><div class="input-container"><input name="email_address" id="email_address" type="text" /><span id="msgbox" style="display:none"></span></div></td>
  </tr>
    <tr>
  	<td><label for="image">Profile Image:</label></td>
	<td><div class="input-container"><input name="user_image" accept="image/jpeg" type="file"></td>
  </tr>  
  <tr>
    <td><label for="pass">New Password:</label></td>
    <td><div class="input-container"><input name="password" id="password" type="password" /></div></td>
  </tr>
  <tr>
    <td><label for="sex-select">I am:</label></td>
    <td>
    <div class="input-container">
    <select name="sex-select" id="sex-select">
    <option value="0">Select Sex:</option>
    <option value="Female">Female</option>
    <option value="Male">Male</option>
    </select>
    </div>  
    </td>
  </tr>
  <tr>
  <td>&nbsp;</td>
  <td><input type="submit" class="greenButton" value="Sign Up" /><img id="loading" src="img/ajax-loader.gif" alt="working.." />
</td>
  </tr> 
  </tbody>
</table>
</form>
<div id="error">
&nbsp;
</div>
</div>
</body>
</html>
