























<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">

<html xmlns:og="http://ogp.me/ns#" xmlns:fb="http://www.facebook.com/2008/fbml" >
<head>
	







		<title>Sephora: Beauty, Skin Care, Makeup, Hair, & Fragrance</title>
	

<meta name="description" content="Sephora.com is the leading online beauty retailer with more than 200 top brands and over 13,000 premier products in the cosmetics, makeup, skin care, hair and fragrance categories.">
<meta name="keywords" content="beauty, cosmetics, skin care, makeup, fragrance, perfume, hair, makeup tips, cosmetics, wrinkles, aging, Sephora collection, shopping, gift sets, concealer, rewards, products, bare Escentuals, stila, make up forever, nars, Clinique, benefit, dior, tarte, urban decay, bliss, Clarisonic, clarins, fresh, lancome, laura merceir, kate Somerville, philosophy, perricone, murad, Smashbox, taylor swift, justin beiber, marc Jacobs, yves saint Laurent, josie maran, boscia, sephora holiday, sephora christmas, sephora holiday products">
<script language="javascript1.2" src="/util/cookies.js"></script>
<script language="javascript1.2" src="/util/util.js"></script>
<script language="javascript" src="/util/aj.js"></script>







<link rel="stylesheet" type="text/css" href="/includes/css/dropdown.css">

		<!-- no style -->
	

		<link rel="stylesheet" type="text/css" href="/includes/css/gw.css">
		<link rel="stylesheet" type="text/css" href="/includes/css/sccModule.css">
		<script language="javascript" type="text/javascript" src="/assets/js/jquery-1.7.1.min.js"></script>
        <script language="javascript" type="text/javascript" src="/includes/js/jquery-colors.js"></script>
        <script language="javascript" type="text/javascript" src="/includes/js/scc.js"></script>
	

        <script lanaguage="javascript">
            var runInitFB = true;

    	</script>

        <meta property="fb:admins" content="1314428622,676965799"/>
        <meta property="og:type" content="website"/>
        <meta property="og:site_name" content="Sephora"/>
        <meta property="og:title" content="Sephora: Beauty, Skin Care, Makeup, Hair, & Fragrance"/>
        <link rel="image_src" href="http://www.sephora.com/assets/global/topNav/blk_logo.gif" />
        <link rel='canonical' href="http://www.sephora.com"/>
    







<script language="javascript1.1" type="text/javascript">
	<!--  
	var cmJv="1.1"; 
	//-->
</script>
<script language="javascript1.2" type="text/javascript">
	<!--  
	var cmJv="1.2"; 
	//-->
</script>

<script language="javascript1.3" type="text/javascript">
	<!--  
	var cmJv="1.3"; 
	//-->
</script>
<script language="javascript1.4" type="text/javascript">
	<!--  
	var cmJv="1.4"; 
	//-->
</script>
<script language="javascript1.5" type="text/javascript">
	<!--  
	var cmJv="1.5"; 
	//-->
</script>
<script language="javascript" type="text/javascript">
	<!--  used in footer.jhtml
	var productID = "";
	//-->
</script>

<script language="javascript" src="/coremetrics/v40/eluminate.js"></script>
<script language="javascript" src="/coremetrics/v40/techprops.js"></script>
<script language="javascript" src="/coremetrics/cmdatatagutils.js"></script>


<script language="javascript" type="text/javascript">
    <!--  
	// detect environment. if production, set production function for cm...
	var host = location.hostname;
	
	if ((host == "www.sephora.com") || (host.indexOf("sephora.com") > -1) || (host.indexOf("sephoria") > -1) || (host.indexOf("safora") > -1)) {
		cmSetProduction(); 
	}
	//-->
</script>





<script language="javascript" src="/numeric/_numeric_.js?release=20100810"></script>



</head>

		<body bgcolor="#FFFFFF" topmargin="0" leftmargin="0" marginwidth="0">

	
<div id="fb-root"></div>
<div class="global">
	
        

					<script language="javascript"><!--
					var inboundURL = window.location.href;

					if (inboundURL.indexOf("us_search") > -1) {
						createCookie("shipPromo",true);
					}

					var x = read_cookie('shipPromo');

					if (x == "true") {
						document.write('<table width="770" border="0" cellpadding="0" cellspacing="0" align="center">');
						document.write('<tr>');
						document.write('<td style="padding-top: 10px;"><a href="/promo/beautybonuses/?int_cid=012412_spb_INTENSE&NOURISH code_beautybonus"><img src="/assets/browse/search/021412_SearchBanner.gif" border="0" width="770" height="60" alt="FREE Clinique Moisture Surge Intense Mini * Use code INTENSE ** FREE Bare Escentuals Mini Trio * While supplies last * Use code BEBARE3 or BEMATTE3 * see all offers &gt;" title="FREE Clinique Moisture Surge Intense Mini * Use code INTENSE ** FREE Bare Escentuals Mini Trio * While supplies last * Use code BEBARE3 or BEMATTE3 * see all offers &gt;"></a></td>');
						document.write('</tr>');
						document.write('</table>');
					}
					--></script>			
		
    

		<!-- used in Lithium iframe header -->
<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr><td valign="top" colspan="2" width="30%" style="background:url(/assets/global/topNav/bg_site.jpg) repeat-x;"></td>
		<td align="center" valign="top" width="770" style="background:url(/assets/global/topNav/bg_site.jpg) repeat-x;">
		




	
<style type="text/css">
.dynamic_hover {cursor: pointer;}
</style>
<script language="javascript">
function btRedir() {
    if ((host == 'qa.sephora.com') || (host == 'preview.sephora.com')) {
	window.location.href = 'http://community.qa.sephora.com/beautyadvice';
    }
    else {
	window.location.href = 'http://community.sephora.com/beautyadvice';
    }    
    
}
</script>

<table border="0" cellpadding="0" cellspacing="0" width="770">
<tr>
		<td><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" border="0" width="280" height="1"></td>
		<td><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" border="0" width="160" height="1"></td>
		<td><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" border="0" width="330" height="1"></td>
	</tr>
<tr><td><a href="/promo/beautybonuses/index.jhtml?pageCode=ws#Everyday Freebies"><img src="http://a248.g.akamai.net/7/248/8278/20110827035133/www.sephora.com/assets/global/topNav/FREESHIPPING_animate.gif" alt="" border="0"></a></td>
	<td align="right" class="copy10">
	<a href="/auth_secure/user/my_profile.jhtml">Sign In</a> or <a href="/auth_secure/user/my_profile.jhtml">Sign Up for Sephora</a>

		    <script language="javascript">
				var customerID = 2808608296;
                if(!wa) {
                    var wa = {};
                }
                wa.userStatus="Not Logged In";
			</script>
        </td>
	<td align="right"><div id="topNavContainer">
	<a href="/"><img src="http://a248.g.akamai.net/7/248/8278/20060906021344/www.sephora.com/assets/global/topNav/tHome.gif" alt="Home" width="45" height="31" border="0"></a><a href="/auth_secure/user/my_profile.jhtml"><img 
		src="http://a248.g.akamai.net/7/248/8278/20060906021344/www.sephora.com/assets/global/topNav/tMyAccount.gif" alt="My Account" width="91" height="31" border="0"></a><a href="/help/stores/index.jhtml"><img 
		src="http://a248.g.akamai.net/7/248/8278/20060906021344/www.sephora.com/assets/global/topNav/tSstores.gif" alt="Sephora Stores" width="58" height="31" border="0"></a><a href="/giftregistry/index.jhtml"><img 
		src="http://a248.g.akamai.net/7/248/8278/20060906021344/www.sephora.com/assets/global/topNav/tGiftReg.gif" alt="Gift Registry" width="91" height="31" border="0"></a><a href="/customer_service/csr_service.jhtml?categoryId=csrService"><img 
		src="http://a248.g.akamai.net/7/248/8278/20060906021344/www.sephora.com/assets/global/topNav/tHelp.gif" alt="Help" width="34" height="31" border="0"></a><div id="myAccount">
			<li class="myAccountList"><a href="/auth_secure/user/my_profile.jhtml"><img src="http://a248.g.akamai.net/7/248/8278/20060906021344/www.sephora.com/assets/global/topNav/tMyAccount.gif" alt="My Account" width="91" height="31" border="0"></a>
				<ul class="myAccountUL">
					<li class="myAccountLi"><a href="/auth_secure/user/order_history.jhtml?actSection=order&actSub=orderView"><span class="topSellers">Order Status</span></a></li>
					<li class="myAccountLi"><a href="/auth_secure/user/lists.jhtml?actSection=lists&actSub=listsFav"><span class="topSellers">Shopping List</span></a></li>

					<li class="myAccountLi"><a href="/auth_secure/registry/manage.jhtml?actSection=lists&actSub=listsReg"><span class="topSellers">My Gift Registry</span></a></li>
				</ul>
			</li>
		</div>
	</div></td></tr>
</table>
<table border="0" cellpadding="0" cellspacing="0" width="770">
<tr bgcolor="#000000">
	<td><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" border="0" width="179" height="1"></td>
	<td><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" border="0" width="575" height="1"></td>

	<td><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" border="0" width="16" height="1"></td>
</tr>
<tr bgcolor="#000000"><td><a href="/"><img src="http://a248.g.akamai.net/7/248/8278/20101221213132/www.sephora.com/assets/global/topNav/blk_logo.gif" alt="Sephora" width="179" height="48" border="0"></a></td>
	<td style="padding-top:5px; padding-right:14px;" align="right" valign="top" class="copyGreyNav copy10"><img src="http://a248.g.akamai.net/7/248/8278/20111101021028/www.sephora.com/assets/global/topNav/cart_icon.gif" alt="" width="13" height="11" border="0">&nbsp; shopping basket 
	<a href="/checkout/cart.jhtml">0
	items</a><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" border="0" width="16" height="1"><a href="/checkout/cart.jhtml">CHECKOUT</a></td>
	<td><img src="http://a248.g.akamai.net/7/248/8278/20100925012938/www.sephora.com/assets/global/topNav/blk_bars.gif" alt="" width="16" height="48" border="0"></td>
</tr>
<tr>
	<td colspan="3">       
		<table border="0" cellpadding="0" cellspacing="0" width="770">

		<tr><td><a href="/browse/section.jhtml?categoryId=B10" onMouseOver="changeNav('makeup','makeupOn');" onMouseOut="changeNav('makeup','makeupOff');"><img src="http://a248.g.akamai.net/7/248/8278/20111223201025/www.sephora.com/assets/global/topNav/nav_makeup_off.gif" width="66" height="24" border="0" id="makeup" name="makeup" alt="Makeup"></a></td>
			<td><a href="/browse/section.jhtml?categoryId=B15" onMouseOver="changeNav('skincare','skincareOn');" onMouseOut="changeNav('skincare','skincareOff');"><img src="http://a248.g.akamai.net/7/248/8278/20111004020005/www.sephora.com/assets/global/topNav/nav_skincare_off.gif" width="73" height="24" border="0" id="skincare" name="skincare" alt="Skincare"></a></td>
			<td><a href="/browse/section.jhtml?categoryId=B23" onMouseOver="changeNav('fragrance','fragranceOn');" onMouseOut="changeNav('fragrance','fragranceOff');"><img src="http://a248.g.akamai.net/7/248/8278/20111004020004/www.sephora.com/assets/global/topNav/nav_fragrance_off.gif" width="85" height="24" border="0" id="fragrance" name="fragrance" alt="Fragrance"></a></td>
			<td><a href="/browse/section.jhtml?categoryId=B65" onMouseOver="changeNav('bathbody','bathbodyOn');" onMouseOut="changeNav('bathbody','bathbodyOff');"><img src="http://a248.g.akamai.net/7/248/8278/20111004020004/www.sephora.com/assets/global/topNav/nav_bath_off.gif" width="89" height="24" border="0" id="bathbody" name="bathbody" alt="Bath and Body"></a></td>
			<td><a href="/browse/section.jhtml?categoryId=C7240" onMouseOver="changeNav('hair','hairOn');" onMouseOut="changeNav('hair','hairOff');"><img src="http://a248.g.akamai.net/7/248/8278/20111004020005/www.sephora.com/assets/global/topNav/nav_hair_off.gif" width="47" height="24" border="0" id="hair" name="hair" alt="Hair"></a></td>
			<td><a href="/browse/section.jhtml?categoryId=B60" onMouseOver="changeNav('tools','toolsOn');" onMouseOut="changeNav('tools','toolsOff');"><img src="http://a248.g.akamai.net/7/248/8278/20111004020005/www.sephora.com/assets/global/topNav/nav_tools_off.gif" width="139" height="24" border="0" id="tools" name="tools" alt="Tools"></a></td>
			<td><a href="/browse/section.jhtml?categoryId=C7790" onMouseOver="changeNav('men','menOn');" onMouseOut="changeNav('men','menOff');"><img src="http://a248.g.akamai.net/7/248/8278/20111223201025/www.sephora.com/assets/global/topNav/nav_men_off.gif" width="46" height="24" border="0" id="men" name="men" alt="Men"></a></td>	
			<td><a href="/browse/section.jhtml?categoryId=B55" onMouseOver="changeNav('gifts','giftsOn');" onMouseOut="changeNav('gifts','giftsOff');"><img src="http://a248.g.akamai.net/7/248/8278/20111223201025/www.sephora.com/assets/global/topNav/nav_gifts_off.gif" width="50" height="24" border="0"  id="gifts" name="gifts" alt="Gifts"></a></td>
			
				<td class="dynamic_hover"><a href="/sephoratv/"><img src="http://a248.g.akamai.net/7/248/8278/20111223201025/www.sephora.com/assets/global/topNav/nav_sephoratv_off.gif" width="101" height="24" border="0" onMouseOver="changeNav('sephoratv','sephoratvOn');" onMouseOut="changeNav('sephoratv','sephoratvOff');" id="sephoratv" name="sephoratv" alt="Sephora TV"></a></td>

			    
			
				<td class="dynamic_hover"><img src="http://a248.g.akamai.net/7/248/8278/20111223201025/www.sephora.com/assets/global/topNav/nav_beautyadvice_off.gif" width="74" height="24" border="0" onclick="btRedir();" onMouseOver="changeNav('beautyadvice','beautyadviceOn');" onMouseOut="changeNav('beautyadvice','beautyadviceOff');" id="beautyadvice" name="beautyadvice" alt="Beauty Advice"></td>
			    
		</tr>
		</table></td></tr>
</table>
		






<table width="770" border="0" cellpadding="0" cellspacing="0" background="/assets/global/topNav/finder_gradient_bkgd.gif">
<tr>
    <td><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" border="0" width="385" height="9"></td>
    <td><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" border="0" width="385" height="9"></td>
</tr>
    <tr>

        <td valign="top">
            <FORM class="searchForm" METHOD="GET" action="/search/search_results.jhtml" onSubmit="setText('navSearchForm')" name="navSearchForm" id="navSearchForm">
                <table border="0" cellpadding="0" cellspacing="0">
                    <tr>
                        <td valign="top">
                            <table border="0" cellpadding="0" cellspacing="0"><tr><td>
                                <input type="hidden" name="command" value="">
                                <input type="hidden" name="attr1" value="">
                                <input type="hidden" name="attr2" value="">

                                <INPUT TYPE="hidden"  value="search" name="/com/sephora/search/endeca/ui/EndecaSearchFormHandler.search"><input type="hidden" name="_D:/com/sephora/search/endeca/ui/EndecaSearchFormHandler.search" value=" ">
                          	<INPUT TYPE="hidden" name="maxRecords" value="18">
                                <INPUT TYPE="hidden" name="recordOffset" value="0">
                                <INPUT TYPE="hidden" name="seeAllCategory" value="false">
                                <input type="text" size="33" maxlength="70" name="searchString" value="" id="sInputTxt"/></td></tr></table></td>
                        <td valign="top"><script language="javascript">writeDivBasedOnBrowser("searchButton", browserDetection);</script><input type="image" src="http://a248.g.akamai.net/7/248/8278/20080507011251/www.sephora.com/assets/global/topNav/finder_search_off.gif" width="53" height="18" border="0" alt="search" onmouseover="this.src='/assets/global/topNav/finder_search_on.gif'" onmouseout="this.src='/assets/global/topNav/finder_search_off.gif'"></td>
                    </tr>
                </table>

            <input type="hidden" name="_DARGS" value="/includes/searchFinder.jhtml"></FORM>
        </td>
    <td align="right">
	
		<table border="0" cellpadding="0" cellspacing="0">
			<tr>
				<td align="right" valign="top"><script language="javascript">writeDivBasedOnBrowser("brandsButton", browserDetection);</script><a href="/brands/complete_list.jhtml"><img src="http://a248.g.akamai.net/7/248/8278/20080507011251/www.sephora.com/assets/global/topNav/finder_brands.gif" alt="" width="45" height="9" border="0"></a></div></td>
				<td align="right">





        <table border="0" cellpadding="0" cellspacing="0">
            <tr>
                <td>
                    <form method="get" name="brandForm" action="/browse/brand_hierarchy.jhtml">
                    
                            <select name="brandId" class="brandFinder" onChange="cmCreateManualLinkClickTag('/browse/brand_hierarchy.jhtml','brandDropDown'); brandForm.submit();">
                                <option value="">CHOOSE BRAND</option>

                                
                                        <option value="fullList">See Complete List &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</option>
                                        <option value="3902">SEPHORA COLLECTION</option>

                                        <option value="fullList">------------------------------</option>
                                        
                                                <option value="21 Drops">21 Drops</option>
                                            
                                                <option value="Acqua Di Parma">Acqua Di Parma</option>
                                            
                                                <option value="Algenist">Algenist</option>
                                            
                                                <option value="ALTERNA">ALTERNA</option>
                                            
                                                <option value="Amazing Cosmetics">Amazing Cosmetics</option>

                                            
                                                <option value="Amika">Amika</option>
                                            
                                                <option value="AmorePacific">AmorePacific</option>
                                            
                                                <option value="Anastasia">Anastasia</option>
                                            
                                                <option value="Andre Walker Hair">Andre Walker Hair</option>
                                            
                                                <option value="Anthony Logistics">Anthony Logistics</option>
                                            
                                                <option value="Aquolina">Aquolina</option>

                                            
                                                <option value="Art of Shaving">Art of Shaving</option>
                                            
                                                <option value="Azzaro">Azzaro</option>
                                            
                                                <option value="BALENCIAGA">BALENCIAGA</option>
                                            
                                                <option value="Balmshell">Balmshell</option>
                                            
                                                <option value="Bare Escentuals">Bare Escentuals</option>
                                            
                                                <option value="BCBGMAXAZRIA">BCBGMAXAZRIA</option>

                                            
                                                <option value="beautyblender">beautyblender</option>
                                            
                                                <option value="Benefit Cosmetics">Benefit Cosmetics</option>
                                            
                                                <option value="Betsey Johnson">Betsey Johnson</option>
                                            
                                                <option value="Billy Jealousy">Billy Jealousy</option>
                                            
                                                <option value="Bite">Bite</option>
                                            
                                                <option value="Blinc">Blinc</option>

                                            
                                                <option value="Bliss">Bliss</option>
                                            
                                                <option value="Bobbi Brown">Bobbi Brown</option>
                                            
                                                <option value="Body Shop">Body Shop</option>
                                            
                                                <option value="Boscia">Boscia</option>
                                            
                                                <option value="Boyfriend">Boyfriend</option>
                                            
                                                <option value="Brazilian Peel">Brazilian Peel</option>

                                            
                                                <option value="Bremenn Research Lab">Bremenn Research Lab</option>
                                            
                                                <option value="Bumble and bumble">Bumble and bumble</option>
                                            
                                                <option value="Burberry">Burberry</option>
                                            
                                                <option value="Buxom">Buxom</option>
                                            
                                                <option value="Bvlgari">Bvlgari</option>
                                            
                                                <option value="By Terry">By Terry</option>

                                            
                                                <option value="Calvin Klein">Calvin Klein</option>
                                            
                                                <option value="Carol's Daughter">Carol's Daughter</option>
                                            
                                                <option value="Carolina Herrera">Carolina Herrera</option>
                                            
                                                <option value="Cartier">Cartier</option>
                                            
                                                <option value="Caudalie">Caudalie</option>
                                            
                                                <option value="CHANEL">CHANEL</option>

                                            
                                                <option value="Charlotte Ronson">Charlotte Ronson</option>
                                            
                                                <option value="Chloe">Chloe</option>
                                            
                                                <option value="Clarins">Clarins</option>
                                            
                                                <option value="Clarisonic">Clarisonic</option>
                                            
                                                <option value="CLEAN">CLEAN</option>
                                            
                                                <option value="ClickR Skin Care">ClickR Skin Care</option>

                                            
                                                <option value="Clinique">Clinique</option>
                                            
                                                <option value="COACH">COACH</option>
                                            
                                                <option value="Couture Colour">Couture Colour</option>
                                            
                                                <option value="Cover FX">Cover FX</option>
                                            
                                                <option value="d.j.v. beautenizer">d.j.v. beautenizer</option>
                                            
                                                <option value="D&amp;G">D&amp;G</option>

                                            
                                                <option value="DDF">DDF</option>
                                            
                                                <option value="Dermadoctor">Dermadoctor</option>
                                            
                                                <option value="Diamancel">Diamancel</option>
                                            
                                                <option value="Diane vonFurstenberg">Diane vonFurstenberg</option>
                                            
                                                <option value="Diesel">Diesel</option>
                                            
                                                <option value="Dior">Dior</option>

                                            
                                                <option value="DKNY">DKNY</option>
                                            
                                                <option value="Dolce &amp; Gabbana">Dolce &amp; Gabbana</option>
                                            
                                                <option value="Donna Karan">Donna Karan</option>
                                            
                                                <option value="Dr. Brandt Skincare">Dr. Brandt Skincare</option>
                                            
                                                <option value="Dr. Dennis Gross">Dr. Dennis Gross</option>

                                            
                                                <option value="Dr. Jart+">Dr. Jart+</option>
                                            
                                                <option value="DSquared2">DSquared2</option>
                                            
                                                <option value="DUO">DUO</option>
                                            
                                                <option value="DuWop">DuWop</option>
                                            
                                                <option value="EDWARD BESS">EDWARD BESS</option>
                                            
                                                <option value="ELLIS FAAS">ELLIS FAAS</option>

                                            
                                                <option value="Escada">Escada</option>
                                            
                                                <option value="Eshu">Eshu</option>
                                            
                                                <option value="Evian">Evian</option>
                                            
                                                <option value="FAIRYDROPS">FAIRYDROPS</option>
                                            
                                                <option value="Fendi">Fendi</option>
                                            
                                                <option value="First Aid Beauty">First Aid Beauty</option>

                                            
                                                <option value="Fresh">Fresh</option>
                                            
                                                <option value="ghd">ghd</option>
                                            
                                                <option value="Giorgio Armani">Giorgio Armani</option>
                                            
                                                <option value="Givenchy">Givenchy</option>
                                            
                                                <option value="GLO">GLO</option>
                                            
                                                <option value="GoClear">GoClear</option>

                                            
                                                <option value="Gucci">Gucci</option>
                                            
                                                <option value="Guerlain">Guerlain</option>
                                            
                                                <option value="Hampton Sun">Hampton Sun</option>
                                            
                                                <option value="Hanae Mori">Hanae Mori</option>
                                            
                                                <option value="Harajuku Lovers">Harajuku Lovers</option>
                                            
                                                <option value="Hello Kitty">Hello Kitty</option>

                                            
                                                <option value="HerCut">HerCut</option>
                                            
                                                <option value="Hourglass">Hourglass</option>
                                            
                                                <option value="Hugo Boss">Hugo Boss</option>
                                            
                                                <option value="Illamasqua">Illamasqua</option>
                                            
                                                <option value="Issey Miyake">Issey Miyake</option>
                                            
                                                <option value="Jack Black">Jack Black</option>

                                            
                                                <option value="Jean Paul Gaultier">Jean Paul Gaultier</option>
                                            
                                                <option value="Jennifer Aniston">Jennifer Aniston</option>
                                            
                                                <option value="JIMMY CHOO">JIMMY CHOO</option>
                                            
                                                <option value="John Varvatos">John Varvatos</option>
                                            
                                                <option value="Jonathan Product">Jonathan Product</option>
                                            
                                                <option value="Josie Maran">Josie Maran</option>

                                            
                                                <option value="Juice Beauty">Juice Beauty</option>
                                            
                                                <option value="Juicy Couture">Juicy Couture</option>
                                            
                                                <option value="Jurlique">Jurlique</option>
                                            
                                                <option value="JUSTIN BIEBER">JUSTIN BIEBER</option>
                                            
                                                <option value="Kate Somerville">Kate Somerville</option>
                                            
                                                <option value="Kate Spade">Kate Spade</option>

                                            
                                                <option value="Kat Von D">Kat Von D</option>
                                            
                                                <option value="Kenzo">Kenzo</option>
                                            
                                                <option value="KeratinPerfect">KeratinPerfect</option>
                                            
                                                <option value="Koh Gen Do">Koh Gen Do</option>
                                            
                                                <option value="Korres">Korres</option>
                                            
                                                <option value="L'Occitane">L'Occitane</option>

                                            
                                                <option value="Lab Series For Men">Lab Series For Men</option>
                                            
                                                <option value="Lacoste">Lacoste</option>
                                            
                                                <option value="Lancome">Lancome</option>
                                            
                                                <option value="Laura Mercier">Laura Mercier</option>
                                            
                                                <option value="LAVANILA">LAVANILA</option>
                                            
                                                <option value="Living Proof">Living Proof</option>

                                            
                                                <option value="Lolita Lempicka">Lolita Lempicka</option>
                                            
                                                <option value="LORAC">LORAC</option>
                                            
                                                <option value="Luminaze">Luminaze</option>
                                            
                                                <option value="MAKE UP FOR EVER">MAKE UP FOR EVER</option>
                                            
                                                <option value="Marc Jacobs">Marc Jacobs</option>
                                            
                                                <option value="Masque*ology">Masque*ology</option>

                                            
                                                <option value="Matte For Men">Matte For Men</option>
                                            
                                                <option value="Michael Kors">Michael Kors</option>
                                            
                                                <option value="Miracle Skin">Miracle Skin</option>
                                            
                                                <option value="ModelCo">ModelCo</option>
                                            
                                                <option value="Ms. &amp; Mrs.">Ms. &amp; Mrs.</option>

                                            
                                                <option value="Murad">Murad</option>
                                            
                                                <option value="Mustela">Mustela</option>
                                            
                                                <option value="nails inc.">nails inc.</option>
                                            
                                                <option value="Narciso Rodriguez">Narciso Rodriguez</option>
                                            
                                                <option value="NARS">NARS</option>
                                            
                                                <option value="Nu Brilliance">Nu Brilliance</option>

                                            
                                                <option value="Nude Skincare">Nude Skincare</option>
                                            
                                                <option value="Ojon">Ojon</option>
                                            
                                                <option value="Ole Henriksen">Ole Henriksen</option>
                                            
                                                <option value="Omorovicza">Omorovicza</option>
                                            
                                                <option value="OPI for SEPHORA">OPI for SEPHORA</option>
                                            
                                                <option value="Origins">Origins</option>

                                            
                                                <option value="Oscar Blandi">Oscar Blandi</option>
                                            
                                                <option value="Ouidad">Ouidad</option>
                                            
                                                <option value="Pacifica">Pacifica</option>
                                            
                                                <option value="Paco Rabanne">Paco Rabanne</option>
                                            
                                                <option value="PAPERSELF">PAPERSELF</option>
                                            
                                                <option value="Paul Yacomine">Paul Yacomine</option>

                                            
                                                <option value="Perfect Formula">Perfect Formula</option>
                                            
                                                <option value="Perfekt">Perfekt</option>
                                            
                                                <option value="Perricone MD">Perricone MD</option>
                                            
                                                <option value="Peter Thomas Roth">Peter Thomas Roth</option>
                                            
                                                <option value="Philosophy">Philosophy</option>
                                            
                                                <option value="Phyto">Phyto</option>

                                            
                                                <option value="Prada">Prada</option>
                                            
                                                <option value="Pucci">Pucci</option>
                                            
                                                <option value="Ralph Lauren">Ralph Lauren</option>
                                            
                                                <option value="REN">REN</option>
                                            
                                                <option value="Rene Furterer">Rene Furterer</option>
                                            
                                                <option value="Rita Hazan">Rita Hazan</option>

                                            
                                                <option value="Robert Piguet">Robert Piguet</option>
                                            
                                                <option value="Rosebud">Rosebud</option>
                                            
                                                <option value="Sachajuan">Sachajuan</option>
                                            
                                                <option value="Sadick">Sadick</option>
                                            
                                                <option value="SEPHORA COLLECTION">SEPHORA COLLECTION</option>
                                            
                                                <option value="Sephora Favorites">Sephora Favorites</option>

                                            
                                                <option value="Serge Normant">Serge Normant</option>
                                            
                                                <option value="Sevin Nyne">Sevin Nyne</option>
                                            
                                                <option value="Shaveworks">Shaveworks</option>
                                            
                                                <option value="Shiseido">Shiseido</option>
                                            
                                                <option value="Silk'n">Silk'n</option>
                                            
                                                <option value="Skyn Iceland">Skyn Iceland</option>

                                            
                                                <option value="Smashbox">Smashbox</option>
                                            
                                                <option value="Soap &amp; Glory">Soap &amp; Glory</option>
                                            
                                                <option value="Sponge">Sponge</option>
                                            
                                                <option value="St. Tropez">St. Tropez</option>
                                            
                                                <option value="Stella McCartney">Stella McCartney</option>

                                            
                                                <option value="Stila">Stila</option>
                                            
                                                <option value="StriVectin">StriVectin</option>
                                            
                                                <option value="Sultra">Sultra</option>
                                            
                                                <option value="Super by Perricone">Super by Perricone</option>
                                            
                                                <option value="Supergoop!">Supergoop!</option>
                                            
                                                <option value="T3">T3</option>

                                            
                                                <option value="Talika">Talika</option>
                                            
                                                <option value="Tanda">Tanda</option>
                                            
                                                <option value="TanTowel">TanTowel</option>
                                            
                                                <option value="TARINA TARANTINO">TARINA TARANTINO</option>
                                            
                                                <option value="Tarte">Tarte</option>
                                            
                                                <option value="Taylor Swift">Taylor Swift</option>

                                            
                                                <option value="Tend Skin">Tend Skin</option>
                                            
                                                <option value="TheBalm">TheBalm</option>
                                            
                                                <option value="Thierry Mugler">Thierry Mugler</option>
                                            
                                                <option value="Tocca">Tocca</option>
                                            
                                                <option value="tokidoki">tokidoki</option>
                                            
                                                <option value="TOM FORD">TOM FORD</option>

                                            
                                                <option value="Too Faced">Too Faced</option>
                                            
                                                <option value="Tricia Sawyer">Tricia Sawyer</option>
                                            
                                                <option value="Tweezerman">Tweezerman</option>
                                            
                                                <option value="Ultraflesh">Ultraflesh</option>
                                            
                                                <option value="Urban Decay">Urban Decay</option>
                                            
                                                <option value="Vera Wang">Vera Wang</option>

                                            
                                                <option value="Versace">Versace</option>
                                            
                                                <option value="Viktor &amp; Rolf">Viktor &amp; Rolf</option>
                                            
                                                <option value="Violent Lips">Violent Lips</option>
                                            
                                                <option value="Yu-Be">Yu-Be</option>
                                            
                                                <option value="Yves Saint Laurent">Yves Saint Laurent</option>

                                            
                                    
                            </select>
                        
                    </form>
                </td>
            </tr>
            <tr>
                <td>
                     
                    <a href="/browse/brand_hierarchy.jhtml" name="brandDropDown">
                        <img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" width="1" height="1" border="0"/>
                    </a>

                </td>
            </tr>
        </table>
</td>
			</tr>
		</table>
		
	</td>
</tr>



</table>

<script language="javascript">
var formNode = document.getElementById('navSearchForm');

function cText(t) {
	// safari: resets text
	if (t.value == "SEARCH: ENTER KEYWORD OR ITEM #") {
		t.value = "";
	}
	// default: resets bg image
	document.getElementById("sInputTxt").className = "inputGW";
	if ("" == t.defaultValue) {
	document.getElementById("sInputTxt").className = "inputGwNoImg";
	}
}

function searchBoxUtil() {
	// check for safari and sets text instead of default bg image
	var agt = navigator.userAgent.toLowerCase();
	if (agt.indexOf("safari") != -1) {
		formNode.searchString.value = "SEARCH: ENTER KEYWORD OR ITEM #";
	} else {
	// clear searchbox
	$('#navSearchForm').reset();
	}
}

function setText(formName) {
 if (
 formNode.searchString.value != "" 
 	) {
	
   formNode.command.value = "text";
   formNode.searchString.value = formNode.attr1.value = formNode.searchString.value.replace(/\'/g,' ');
 }
}

</script>
</td>
		<td valign="top" width="30%" colspan="2" style="background:url(/assets/global/topNav/bg_site.jpg) repeat-x;"></td></tr>
	<tr><td class="gradientTop" width="30%"><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" border="0" width="1" height="250"></td>
	<td rowspan="3" width="17"><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" border="0" width="17" height="1"></td>
	<td valign="top" rowspan="3">
	

<script language="javascript">
    if(runInitFB) {
        if(!wa) {
            wa = {};
        }
        wa.referrer = document.referrer;

        window.fbAsyncInit = function() {
            FB.init({
                appId: "124755580884988",
                status: true,
                cookie: true,
                xfbml: true
            });
        };
        (function() {
            var e = document.createElement('script'); e.async = true;
            e.src = document.location.protocol + '//connect.facebook.net/en_US/all.js';
            document.getElementById('fb-root').appendChild(e);
        }());
    }

</script>

<script language="javascript">
<!--
	var pageID = "Home";
	cmCreateTechPropsTag(pageID, "C7010");
// -->
</script>
	



<table width="770" border="0" cellpadding="0" cellspacing="0" align="center">
<tr><td colspan="3">
<script type="text/javascript">
/* Tab Names. Leftover AJAX Tab stuff. No need to update for Redesign 4/21/09 */
	var tabN = "tab 1";
	var tab1Name = "tab1";
	var tab2Name = "tab2";
	var tab3Name = "tab3";
	var tab4Name = "tab4";

	function omniProdCode(pId,brandId,pName,pCount,ptabName) {
		var omprodId = pId.innerHTML;
		var omprodName = brandId.innerHTML + " " +pName.innerHTML;
		var omcatName = ptabName.innerHTML;
		var omSection = "gateway:" + omcatName+ ":" + pCount.innerHTML;
		var omprodString = "';" + omprodId +";;;;evar3="+omcatName+"|evar19="+pCount.innerHTML+"|evar20="+omSection+"'";
		var replaceChar = /'/g ;  // any occurence of single quotes in the string would be matched

		if (replaceChar.test(omprodName)) {
			omprodName = omprodName.replace(replaceChar,'\'') ;
		}
		var omhost = location.hostname;
		if ((omhost == "www.sephora.com") || (omhost.indexOf("sephora.com") > -1) || (omhost.indexOf("sephoria") > -1) || (omhost.indexOf("safora") > -1) || (omhost.indexOf("shop.sephora.com") > -1) || (omhost.indexOf("sephora.p.delivery.net") > -1)) {
			var omSuite="sephoracom";
		} else { var omSuite="sephoradev"; }
		s=s_gi(omSuite); s.linkTrackVars='eVar3,eVar19,eVar20,products'; s.products=omprodString; s.tl(this,'o',omprodName);
	}	
</script>
<table width="770" border="0" cellpadding="0" cellspacing="0">
	<tr><td valign="top" rowspan="2" align="left"><a href="/go/hotnow/" alt="SEPHORA HOT NOW * Check out our edit of the newest, the latest, the most buzzed-about beauty &gt;" title="SEPHORA HOT NOW * Check out our edit of the newest, the latest, the most buzzed-about beauty &gt;" style="border:0px;"><img src="http://a248.g.akamai.net/7/248/8278/20120203062135/www.sephora.com/assets/browse/homepage/gwHero_020612.jpg"  style="border:0px;" /></a></td>
	    <td valign="top"><img src="http://a248.g.akamai.net/7/248/8278/20120130003146/www.sephora.com/assets/browse/homepage/gwMoreWays_013112.gif" width="259" height="170" border="0" usemap="#moreWaysToShop"></td></tr>
	<tr><td valign="top"><img src="http://a248.g.akamai.net/7/248/8278/20120211225731/www.sephora.com/assets/browse/homepage/gwSpecial_021412.gif" width="259" height="185" border="0" usemap="#gwSpecials"></td></tr>
	<tr><td valign="top" colspan="2" style="padding-bottom: 5px;"><img src="http://a248.g.akamai.net/7/248/8278/20111223201023/www.sephora.com/assets/browse/homepage/gwFreeBar_US_122711.jpg" width="770" height="24" border="0" usemap="#gwFreeBar"/></td></tr>

</table>


<map name="home">
	<area shape="rect" coords="64,305,257,333" href="http://apps.facebook.com/egiftsocial/?url=sephora&mp=1" target="_new" alt="Give a gift on Facebook" title="Give a gift on Facebook"    />
	<area shape="rect" coords="263,305,439,333" href="/browse/product.jhtml?id=P5612&categoryId=B55&SubId=GC" alt="E-mail a gift certificate" title="E-mail a gift certificate"    />
	<area shape="rect" coords="0,0,509,347" href="/browse/product.jhtml?id=P5612&categoryId=B55&SubId=GC" alt="Instant Cheer * Send a last minute gift, right now, via e-mail or Facebook" title="Instant Cheer * Send a last minute gift, right now, via e-mail or Facebook"    />
</map>

<map name="gwSpecials">
	<area shape="CIRCLE" coords="47,49,37" href="/promo/beautybonuses2/index.jhtml" alt="WEEKLY SPECIALS see more &gt;" title="WEEKLY SPECIALS see more &gt;">
	<area coords="0,0,259,180" href="/promo/beautybonuses2/index.jhtml" alt="COMPLEXION PERFECTION  * FREE Bare Escentuals Travel-Size Trio * Choose from Original or Matte ** Moisture to the Max * FREE Clinique Moisture Surge Intense Mini * Use code INTENSE * SEE MORE &gt;" title="COMPLEXION PERFECTION  * FREE Bare Escentuals Travel-Size Trio * Choose from Original or Matte ** Moisture to the Max * FREE Clinique Moisture Surge Intense Mini * Use code INTENSE * SEE MORE &gt;">   

</map>

<map name="moreWaysToShop">
	<area coords="22,45,119,117" alt="more ways to shop">
	<area coords="109,2,249,25" href="/checkout/samples.jhtml" alt="Today's FREE Samples">
	<area coords="110,26,249,50" href="/browse/section.jhtml?categoryId=C8330" alt="Just Arrived">
	<area coords="109,51,248,73" href="/go/hotnow/" alt="Hot Now">
	<area coords="109,74,247,96" href="/browse/section.jhtml?categoryId=C11910" alt="Editors Obsessions">
	<area coords="109,96,247,119" href="http://reviews.sephora.com/8723/allreviews.htm" alt="Top-Rated Products">
	<area coords="108,119,247,143" href="/beautyinsider/index.jhtml" alt="Beauty Insider Offers">

	<area coords="110,143,246,167" href="/browse/section.jhtml?categoryId=C10214" alt="Sale">
</map>
<map name="gwFreeBar">
	<area href="/promo/beautybonuses2/index.jhtml" alt="free RETURNS" coords="0,0,188,24">
	<area href="/promo/beautybonuses2/index.jhtml" alt="free SHIPPING OVER $50" coords="188,0,501,24">
	<area href="/checkout/samples.jhtml" alt="3 free SAMPLES" coords="501,0,770,24">
</map></td></tr>
  <tr><td class="dotsV"><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" width="1" height="1" border="0"></td>
  <td class="dotsH" style="padding-bottom:8px;"><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" width="1" height="1" border="0"></td>
  <td class="dotsV"><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" width="1" height="1" border="0"></td></tr>

 <tr><td class="dotsV"><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" width="1" height="1" border="0"></td>
  <td valign="top"><div id="products">


















		
	






<table width="768" cellspacing="0" cellpadding="0" border="0">
 <tr>
		
				
  <td><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" width="1" height="1" border="0"></td>
  <td style="padding-top: 5px;"><img src="http://a248.g.akamai.net/7/248/8278/20111018201419/www.sephora.com/assets/browse/homepage/gwEditorsP_101811.gif" border="0" alt="editor's picks"></td>
  <td valign="top" colspan="7"><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" width="1" height="1" border="0"></td>
  <td valign="top" align="right" colspan="3" style="padding-right:10;padding-bottom:2px;"><!-- top pagination -->

						










   <span class="pagination">



		

		

		
				
   1
					
			
				
			
				
			 
   of 

		
				
			
				
			
				
   3
					
			
	


   &nbsp;<a href="javascript:load('/browse/templates/components/grid_hp.jhtml?categoryId=C19172&block=2&cmId=C7010', 'products')"><img src="http://a248.g.akamai.net/7/248/8278/20070806234118/www.sephora.com/assets/global/paginationNext.gif" width="15" height="14" border="0" alt="&gt;" style="vertical-align:middle"></a>
	
   </span>
						
					
			
 </tr>
 <tr>
  <td colspan="12"><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" width="1" height="10" border="0"></td>
 </tr>

	
 <tr>
 	
		
					
 <div id="ompId1" style="display:none;">P305135</div>
 <div id="ombrandId1" style="display:none;">Josie Maran</div>
 <div id="ompName1" style="display:none;">Beautiful Bronze Kit ($74 Value)</div>
 <div id="omCount1" style="display:none;">1</div>
 <div id="ompTab1" style="display:none;"></div>
  <td>&nbsp;</td>

  <td valign="top"><a href="/browse/product.jhtml?id=P305135&categoryId=C7010" onClick="omniProdCode(ompId1,ombrandId1,ompName1,omCount1,ompTab1);"><img src="http://a248.g.akamai.net/7/248/8278/20120107040054/www.sephora.com/assets/dyn/product/P305135/P305135_lg.jpg" border="0" alt="Beautiful Bronze Kit ($74 Value)" width="150" class="fivePixBuff"></a><br>

   <a href="/browse/product.jhtml?id=P305135&categoryId=C7010" onClick="omniProdCode(ompId1,ombrandId1,ompName1,omCount1,ompTab1);">Josie Maran Beautiful Bronze Kit ($74 Value)</a>, $36</td>
  <td><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" width="1" height="1" border="0"></td>
			
	
		
					
 <div id="ompId2" style="display:none;">P305103</div>
 <div id="ombrandId2" style="display:none;">T3</div>
 <div id="ompName2" style="display:none;">Straight Laced SinglePass Styling Set (Value $200)</div>

 <div id="omCount2" style="display:none;">2</div>
 <div id="ompTab2" style="display:none;"></div>
  <td>&nbsp;</td>
  <td valign="top"><a href="/browse/product.jhtml?id=P305103&categoryId=C7010" onClick="omniProdCode(ompId2,ombrandId2,ompName2,omCount2,ompTab2);"><img src="http://a248.g.akamai.net/7/248/8278/20120107040053/www.sephora.com/assets/dyn/product/P305103/P305103_lg.jpg" border="0" alt="Straight Laced SinglePass Styling Set (Value $200)" width="150" class="fivePixBuff"></a><br>

   <a href="/browse/product.jhtml?id=P305103&categoryId=C7010" onClick="omniProdCode(ompId2,ombrandId2,ompName2,omCount2,ompTab2);">T3 Straight Laced SinglePass Styling Set (Value $200)</a>, $160</td>
  <td><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" width="1" height="1" border="0"></td>
			
	
		
					
 <div id="ompId3" style="display:none;">P301802</div>

 <div id="ombrandId3" style="display:none;">Hourglass</div>
 <div id="ompName3" style="display:none;">Immaculate Liquid Powder Foundation Mattifying Oil Free</div>
 <div id="omCount3" style="display:none;">3</div>
 <div id="ompTab3" style="display:none;"></div>
  <td>&nbsp;</td>
  <td valign="top"><a href="/browse/product.jhtml?id=P301802&categoryId=C7010" onClick="omniProdCode(ompId3,ombrandId3,ompName3,omCount3,ompTab3);"><img src="http://a248.g.akamai.net/7/248/8278/20111215040207/www.sephora.com/assets/dyn/product/P301802/P301802_lg.jpg" border="0" alt="Immaculate Liquid Powder Foundation Mattifying Oil Free" width="150" class="fivePixBuff"></a><br>

   <a href="/browse/product.jhtml?id=P301802&categoryId=C7010" onClick="omniProdCode(ompId3,ombrandId3,ompName3,omCount3,ompTab3);">Hourglass Immaculate Liquid Powder Foundation Mattifying Oil Free</a>, $55</td>

  <td><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" width="1" height="1" border="0"></td>
			
	
		
					
 <div id="ompId4" style="display:none;">P294401</div>
 <div id="ombrandId4" style="display:none;">Ole Henriksen</div>
 <div id="ompName4" style="display:none;">Seven Skincare Sensations ($115 Value)</div>
 <div id="omCount4" style="display:none;">4</div>
 <div id="ompTab4" style="display:none;"></div>
  <td>&nbsp;</td>

  <td valign="top"><a href="/browse/product.jhtml?id=P294401&categoryId=C7010" onClick="omniProdCode(ompId4,ombrandId4,ompName4,omCount4,ompTab4);"><img src="http://a248.g.akamai.net/7/248/8278/20110804030128/www.sephora.com/assets/dyn/product/P294401/P294401_lg.jpg" border="0" alt="Seven Skincare Sensations ($115 Value)" width="150" class="fivePixBuff"></a><br>

   <a href="/browse/product.jhtml?id=P294401&categoryId=C7010" onClick="omniProdCode(ompId4,ombrandId4,ompName4,omCount4,ompTab4);">Ole Henriksen Seven Skincare Sensations ($115 Value)</a>, $55</td>
  <td><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" width="1" height="1" border="0"></td>
			
	
 </tr>
 <tr>
  <td colspan="12"><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" width="1" height="15" border="0"></td>
 </tr>

	
 <tr>
 	
		
					
 <div id="ompId5" style="display:none;">P303311</div>
 <div id="ombrandId5" style="display:none;">Charlotte Ronson</div>
 <div id="ompName5" style="display:none;">2 X A Charm Blush/Bronzer</div>
 <div id="omCount5" style="display:none;">5</div>
 <div id="ompTab5" style="display:none;"></div>
  <td>&nbsp;</td>

  <td valign="top"><a href="/browse/product.jhtml?id=P303311&categoryId=C7010" onClick="omniProdCode(ompId5,ombrandId5,ompName5,omCount5,ompTab5);"><img src="http://a248.g.akamai.net/7/248/8278/20111221040847/www.sephora.com/assets/dyn/product/P303311/P303311_lg.jpg" border="0" alt="2 X A Charm Blush/Bronzer" width="150" class="fivePixBuff"></a><br>

   <a href="/browse/product.jhtml?id=P303311&categoryId=C7010" onClick="omniProdCode(ompId5,ombrandId5,ompName5,omCount5,ompTab5);">Charlotte Ronson 2 X A Charm Blush/Bronzer</a>, $26</td>
  <td><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" width="1" height="1" border="0"></td>
			
	
		
					
 <div id="ompId6" style="display:none;">P302300</div>
 <div id="ombrandId6" style="display:none;">Dr. Dennis Gross Skincare</div>
 <div id="ompName6" style="display:none;">Active Vitamin D Serum-Oil</div>

 <div id="omCount6" style="display:none;">6</div>
 <div id="ompTab6" style="display:none;"></div>
  <td>&nbsp;</td>
  <td valign="top"><a href="/browse/product.jhtml?id=P302300&categoryId=C7010" onClick="omniProdCode(ompId6,ombrandId6,ompName6,omCount6,ompTab6);"><img src="http://a248.g.akamai.net/7/248/8278/20111115040350/www.sephora.com/assets/dyn/product/P302300/P302300_lg.jpg" border="0" alt="Active Vitamin D Serum-Oil" width="150" class="fivePixBuff"></a><br>

   <a href="/browse/product.jhtml?id=P302300&categoryId=C7010" onClick="omniProdCode(ompId6,ombrandId6,ompName6,omCount6,ompTab6);">Dr. Dennis Gross Skincare Active Vitamin D Serum-Oil</a>, $65</td>
  <td><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" width="1" height="1" border="0"></td>
			
	
		
					
 <div id="ompId7" style="display:none;">P305102</div>

 <div id="ombrandId7" style="display:none;">Chloe</div>
 <div id="ompName7" style="display:none;">L'Eau de Chlo&amp;#233;</div>
 <div id="omCount7" style="display:none;">7</div>
 <div id="ompTab7" style="display:none;"></div>
  <td>&nbsp;</td>
  <td valign="top"><a href="/browse/product.jhtml?id=P305102&categoryId=C7010" onClick="omniProdCode(ompId7,ombrandId7,ompName7,omCount7,ompTab7);"><img src="http://a248.g.akamai.net/7/248/8278/20120124040204/www.sephora.com/assets/dyn/product/P305102/P305102_lg.jpg" border="0" alt="L'Eau de Chlo&amp;#233;" width="150" class="fivePixBuff"></a><br>

   <a href="/browse/product.jhtml?id=P305102&categoryId=C7010" onClick="omniProdCode(ompId7,ombrandId7,ompName7,omCount7,ompTab7);">Chloe L'Eau de Chlo&#233;</a>, $40 - $85</td>
  <td><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" width="1" height="1" border="0"></td>
			
	
		
					
 <div id="ompId8" style="display:none;">P302628</div>
 <div id="ombrandId8" style="display:none;">Anastasia</div>
 <div id="ompName8" style="display:none;">Brow Enhancing Serum Advanced</div>
 <div id="omCount8" style="display:none;">8</div>

 <div id="ompTab8" style="display:none;"></div>
  <td>&nbsp;</td>
  <td valign="top"><a href="/browse/product.jhtml?id=P302628&categoryId=C7010" onClick="omniProdCode(ompId8,ombrandId8,ompName8,omCount8,ompTab8);"><img src="http://a248.g.akamai.net/7/248/8278/20111202041237/www.sephora.com/assets/dyn/product/P302628/P302628_lg.jpg" border="0" alt="Brow Enhancing Serum Advanced" width="150" class="fivePixBuff"></a><br>

   <a href="/browse/product.jhtml?id=P302628&categoryId=C7010" onClick="omniProdCode(ompId8,ombrandId8,ompName8,omCount8,ompTab8);">Anastasia Brow Enhancing Serum Advanced</a>, $45</td>
  <td><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" width="1" height="1" border="0"></td>
			
	
 </tr>
 <tr>

  <td colspan="12"><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" width="1" height="15" border="0"></td>
 </tr>
	
 <tr>
  <td><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" width="20" height="10" border="0"></td>
  <td><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" width="150" height="1" border="0"></td>
  <td><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" width="25" height="1" border="0"></td>
  <td><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" width="20" height="10" border="0"></td>
  <td><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" width="150" height="1" border="0"></td>
  <td><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" width="25" height="1" border="0"></td>

  <td><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" width="20" height="10" border="0"></td>
  <td><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" width="150" height="1" border="0"></td>
  <td><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" width="25" height="1" border="0"></td>
  <td><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" width="20" height="10" border="0"></td>
  <td><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" width="150" height="1" border="0"></td>
  <td><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" width="13" height="1" border="0"></td>
 </tr>
</table>
	</div></td>

  <td class="dotsV"><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" width="1" height="1" border="0"></td></tr>
  <tr><td class="dotsH" colspan="3" style="padding-bottom:15px"><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" width="1" height="1" border="0"></td></tr>
  <tr><td colspan="3">



		
<img src="http://a248.g.akamai.net/7/248/8278/20120203062120/www.sephora.com/assets/browse/features/C7010_1_020612.jpg" width="188" height="211" border="0" usemap="#C7010_1" style="margin-right: 6px;" /><img src="/assets/browse/features/C7010_2_021412.jpg" width="188" height="211" border="0" usemap="#C7010_2" style="margin-right: 6px;" /><img src="http://a248.g.akamai.net/7/248/8278/20120203062124/www.sephora.com/assets/browse/features/C7010_3_020612.jpg" width="188" height="211" border="0" usemap="#C7010_3" style="margin-right: 6px;" /><img src="/assets/browse/features/C7010_4_020612.jpg" width="188" height="211" border="0" usemap="#C7010_4" style="margin-right: 0px;" />

<map name="C7010_1">
 <area coords="0,0,188,211" href="/browse/section.jhtml?categoryId=C21460  " alt="More to Love * Our most generous sizes at even greater values &gt;" title="More to Love * Our most generous sizes at even greater values &gt;" target="">
</map>

<map name="C7010_2">
 <area coords="0,0,188,211" href="http://community.sephora.com/t5/The-Swatch-Board/bd-p/swatchboard" alt="The Swatch Board on BeautyTalk * See your favorite shades on every skintone &gt;" title="The Swatch Board on BeautyTalk * See your favorite shades on every skintone &gt;" target="">
</map>
<map name="C7010_3">
 <area coords="0,0,188,211" href="/browse/brand_hierarchy.jhtml?brandId=JIMMY+CHOO" alt="Brand New: Jimmy Choo * The essence of pure luxury" title="Brand New: Jimmy Choo * The essence of pure luxury" target="">
</map>
<map name="C7010_4">
 <area coords="0,0,188,211" href="/go/skinnovations" alt="Skincare Breakthroughs * See the difference with our most advanced formulas yet &gt;" title="Skincare Breakthroughs * See the difference with our most advanced formulas yet &gt;" target="">
</map>
<map name="C7010_5">
 <area coords="0,0,382,211" href="/sephoratv/" alt="Introducing Sephora TV Turn Beauty On * Advice, trends, how-to's-watch &amp; get inspired" title="Introducing Sephora TV Turn Beauty On * Advice, trends, how-to's-watch &amp; get inspired" target="">
</map>
	

</td></tr>
</table>
<script language="javascript">
<!--
	// CI vars
	var CI_PageType = "Category";
	var CI_CatID = "C19172";
	var CI_CatName = "Home";
				
	if (CI_CatID != "" && CI_CatID.length > 0) {
		document.write('<sc'+'ript src="http://cts.channelintelligence.com/19786243_landing.js"><\/script>');
	}
// -->
</script> 
<script type="text/javascript">
<!--
var axel = Math.random() + "";
var a = axel * 10000000000000;
document.write('<iframe src="http://fls.doubleclick.net/activityi;src=2608263;type=homep616;cat=sepho113;ord=' + a + '?" width="1" height="1" frameborder="0"></iframe>');
// -->
</script>











<style type="text/css">
#footerContainer {width:770px; }
.footerContent {float:left; padding-left:7px; width:175px; border-right:1px solid #cccccc; height:77px; margin: 10px 0px 12px 0px; }
.footerContent.last {float:left; margin-top:10px; width:140px; border:none;}
.footerContent a {text-decoration:none; }
.footerContent ul li {list-style:none; line-height:16px; }
.footerContent .flag  {background:url(/assets/global/footer/flag_ca.gif) no-repeat left; }
.flame {border:none; padding:12px 30px 0px 10px; float:left; }
.copy-right {clear:both; text-align:center; border-top:1px solid #cccccc; padding-top:6px; line-height: 16px; }
.dynamic_hover {cursor: pointer;}
</style>
<script language="javascript">
function cText(t) {
    if (t.value == t.defaultValue) {
        t.value = "";
    }
}

function btRedir() {
    if ((host == 'qa.sephora.com') || (host == 'preview.sephora.com')) {
	window.location.href = 'http://community.qa.sephora.com/beautyadvice';
    }
    else {
	window.location.href = 'http://community.sephora.com/beautyadvice';
    }    
    
}
</script>
<map name="social_media">
<area alt="Access Exclusive Fan Friday Offers" coords="1,2,233,48" href="http://www.facebook.com/Sephora?sk=app_4949752878" target="_blank">
<area alt="DiscoverToday's Obsession" coords="256,2,503,49" href="/go/iPhone/" target="_parent">
<area alt="Shop our interactive Beauty Report" coords="529,2,767,49" href="/go/ipad/" target="_parent">
</map>
<map name="social_media_ca">
<area alt="'Like' us for the latest Sephora buzz" coords="1,2,233,48" href="http://www.facebook.com/Sephora" target="_blank">
<area alt="DiscoverToday's Obsession" coords="256,2,503,49" href="/go/iPhone/">
<area alt="Shop our interactive Beauty Report" coords="529,2,767,49" href="/go/ipad/">
</map>
<table border="0" cellpadding="0" cellspacing="0" width="770" align="center">
<tr><td style="padding-top: 15px;"><div style="background-color: #333333;"><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" border="0" width="770" height="1" alt="" /></div>
	<div style="width: 770px; padding-top: 10px;"><img src="http://a248.g.akamai.net/7/248/8278/20111025025323/www.sephora.com/assets/global/footer/social_banner_102511.jpg" border="0" usemap="#social_media"/></div>

		<div style="width: 770px; margin-top: 10px;"><img src="http://a248.g.akamai.net/7/248/8278/20111025025323/www.sephora.com/assets/global/footer/footer_grad_102511.gif" border="0" /></div>
	<div style="width: 770px; padding-top: 5px;">
	<div style="float: left;"><fb:like href="http://www.facebook.com/sephora" show_faces="false" layout="button_count" width="55px"></fb:like></div>
	<div style="float: left; width: 35px;"><a href="http://www.YouTube.com/Sephora" target="_blank"><img src="http://a248.g.akamai.net/7/248/8278/20111025025322/www.sephora.com/assets/global/footer/btn_yt_102511.gif" border="0" alt="Follow us on Youtube"/></a></div>
	<div style="float: left; width: 35px; padding-bottom: 6px;"><a href="http://twitter.com/sephora" target="_blank"><img src="http://a248.g.akamai.net/7/248/8278/20111025025322/www.sephora.com/assets/global/footer/btn_tw_102511.gif" border="0" alt="Follow us on Twitter"/></a></div>
	<div style="float: right;"><form class="emailForm" action="/util/lookup.jhtml" method="POST">
	<div style="float: left; padding-right: 7px;"><img src="http://a248.g.akamai.net/7/248/8278/20111025025322/www.sephora.com/assets/global/footer/btn_env_102511.gif" border="0" alt="" /></div><div style="float: left;"><input type="text" name="emailAddress" size="32" class="inputStd" value="Enter your email for special offers" onFocus="cText(this);" style="background-color: #e2e0e1; border: 3px solid #e2e0e1;"/></div><div style="float: left; padding-left: 4px;"><input id="emailButton" type="image" src="http://a248.g.akamai.net/7/248/8278/20111025025322/www.sephora.com/assets/global/footer/btn_go_102511.gif" border="0" alt="ENTER"></div></form></div></div>
	<div style="width: 770px; clear: both; background-color: #000000;"><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" border="0" width="1" height="3" alt="" /></div>
	<div id="footerContainer">

	<div class="flame"><img src="http://a248.g.akamai.net/7/248/8278/20111223201024/www.sephora.com/assets/global/footer/sephora_flame_122711.gif" border="0" alt="" /></div>
	<div class="footerContent">
	<ul><li><a href="/help/about_sephora.jhtml">About Sephora</a></li>
	<li><a href="/help/about_sephora.jhtml?location=jobs">Jobs</a></li>
	<li><a href="/help/stores/index.jhtml">Store Locator &amp; Events</a></li>
	<li><a href="/international.jhtml">Sephora International</a></li>

	<li class="flag"><a href="/canada/">Canada</a></li></ul></div>
	<div class="footerContent">
	<ul>
	
	
	
	<li><a href="/help/supplychaintransparency.jhtml">Supply&nbsp;Chain&nbsp;Transparency</a></li>
	
	
	<li><a href="/browse/product.jhtml?id=P37590&categoryId=B55&SubId=GCard">Gift Card</a></li>
	<li><a href="/customer_service/copy/siteindex.jhtml">Site Index</a></li>

	<li><a href="/browse/affiliate/affiliate_application.jhtml">Affiliates</a></li>
	<li><a href="/university/index.jhtml">Sephora University</a></li></ul></div>
	<div class="footerContent">
	<ul><li><a href="/secure/user/login.jhtml?next=my_profile&nextpage=/auth_secure/user/my_profile.jhtml">My Account</a></li>
	<li><a href="/beautyinsider/index.jhtml">Beauty Insider</a></li>
	<li><a href="/secure/user/login.jhtml?next=lists&nextpage=/auth_secure/user/lists.jhtml">My Shopping List</a></li>

	<li><a href="/secure/user/login.jhtml?next=order_history&nextpage=/auth_secure/user/order_history.jhtml">Order Status</a></li></ul></div>
	<div class="footerContent last">
	<ul><li><a href="/customer_service/csr_controller.jhtml?csrSection=shipping&csrSub=shipCosts">Shipping</a></li>

	<li><a href="/go/beautystudio/index.jhtml">In&nbsp;Store&nbsp;Beauty&nbsp;Services</a></li>


	<li><a href="/customer_service/csr_service.jhtml?SectionID=csrService">Customer Service</a></li>
	<li><a href="/customer_service/csr_controller.jhtml?csrSection=contact&csrSub=contactCs">Contact Us</a></li></ul></div>	
	<div class="copy-right global copy10">Copyright &copy; 1999 - 2012 Sephora USA, Inc. ALL RIGHTS RESERVED. <a href="/includes/legal_notice.jhtml">Terms of use</a>. <a href="/includes/privacy_policy.jhtml">Privacy Policy</a><br>1-877-737-4672<br><br></div></div>
	</tr></td>

</table>
</td>
<td rowspan="3"><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" border="0" width="17" height="1"></td>
<td class="gradientTop" width="30%"><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" border="0" width="1" height="250"></td></tr>
	<tr><td><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" border="0" width="1" height="1"></td>
	<td><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" border="0" width="1" height="1"></td></tr>
	<tr><td class="gradientBottom"><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" border="0" width="1" height="250"></td>
	<td class="gradientBottom"><img src="http://a248.g.akamai.net/7/248/8278/20030812002803/www.sephora.com/assets/global/p.gif" border="0" width="1" height="250"></td></tr>
</table>
</div><!-- end class=global -->

<!-- coremetrics default PageViewTag -->

        
        <script language="javascript">
            <!--

                    
            var text = window.location.href;
            var searchString = '';

            function removeSessionId(str) {
                if (text.indexOf(";") > -1){
                    first = getQueryStringFirst(str);
                    second = getQueryStringSecond(str);
                    return(first+second);
                } else {
                    return (removeDomain(str));
                }
            }

            function getQueryStringFirst(str) {
                la = str.indexOf(".com")+4;
                ra = str.lastIndexOf(";");
                first = str.substring(la, ra);
                return first;
            }

            function getQueryStringSecond(str) {
                rb = str.lastIndexOf("?");
                second = str.substring(rb,str.length);
                return second;
            }

            function removeDomain(str) {
                rb = str.lastIndexOf(".com")+4;
                url = str.substring(rb,str.length);
                return url;
            }

            if (productID) {
            } else if (pageID == "Home") {
            } else if (pageID == "Search Results") {
                cmCreatePageviewTag(pageID, categoryID, searchString, searchTotal);
            } else if (searchString) {
                cmCreatePageviewTag(pageID, categoryID, searchString, null);
            } else if (pageID == null) {
                var pageID = removeSessionId(text);
                var categoryID = 'none';
                cmCreatePageviewTag(pageID, categoryID, null, null);
            } else {
                cmCreatePageviewTag(pageID, categoryID, null, null);
            }

            // -->
        </script>
    

        <noscript>
            <h1>Fragrance - Skin Care - Skin Care Product - Cosmetics - Facial Skin Care Product</h1>
            <p>
                Sephora.com carries the finest in <b>Skin Care Product</b> lines, along with the most popular
                <b> <a href="http://www.sephora.com">Cosmetics</a></b> and
                <b><a href="http://www.sephora.com">Fragrance</a></b>
                collections available.  Our Luxury
                <b><a href="http://www.sephora.com">Skin Care</a></b> and
                <b><a href="http://www.sephora.com">Make up</a></b>
                products make your life prettier.
            </p>
            <p>
                <a href="http://www.sephora.com">Fragrance</a> |
                <a href="http://www.sephora.com/browse/section.jhtml?categoryId=B10">Make Up</a> |
                <a href="http://www.sephora.com/browse/section.jhtml?categoryId=B15">Facial Skin Care</a> |
                <a href="http://www.sephora.com/browse/section.jhtml?categoryId=B23">Perfume</a> |
                <a href="http://www.sephora.com/browse/section.jhtml?categoryId=B65">Body Lotion</a> |
                <a href="http://www.sephora.com/browse/section.jhtml?categoryId=C7240">Hair Care</a> |
                <a href="http://www.sephora.com/browse/section.jhtml?categoryId=B60">Make up Cases</a> |
                <a href="http://www.sephora.com/browse/section.jhtml?categoryId=C7790">Men's Cologne</a> |
                <a href="http://www.sephora.com/browse/section.jhtml?categoryId=S550104">Gifts for Her</a> |
                <a href="http://www.sephora.com/browse/section.jhtml?categoryId=C7327">Beauty Care</a> |
                <a href="http://www.sephora.com/browse/section.jhtml?categoryId=C8330">Beauty Products</a> |
                <a href="http://www.sephora.com/browse/tt/index.jhtml">Beauty Tips</a>
            </p>
        </noscript>
    
<!-- AKAMAIZED NAV CODE -->
<div style="display: none;">
    <img src="http://a248.g.akamai.net/7/248/8278/20111223201025/www.sephora.com/assets/global/topNav/nav_makeup_off.gif" id="makeupOff" name="makeup" alt="Makeup"><br />
    <img src="http://a248.g.akamai.net/7/248/8278/20111223201025/www.sephora.com/assets/global/topNav/nav_makeup_on.gif"  id="makeupOn" name="makeup" alt="Makeup"><br />
    <img src="http://a248.g.akamai.net/7/248/8278/20111004020005/www.sephora.com/assets/global/topNav/nav_skincare_off.gif"  id="skincareOff" name="skincare" alt="Skincare"><br />
    <img src="http://a248.g.akamai.net/7/248/8278/20111004020005/www.sephora.com/assets/global/topNav/nav_skincare_on.gif"  id="skincareOn" name="skincare" alt="Skincare"><br />

    <img src="http://a248.g.akamai.net/7/248/8278/20111004020004/www.sephora.com/assets/global/topNav/nav_fragrance_off.gif"  id="fragranceOff" name="fragrance" alt="Fragrance"><br />
    <img src="http://a248.g.akamai.net/7/248/8278/20111004020005/www.sephora.com/assets/global/topNav/nav_fragrance_on.gif"  id="fragranceOn" name="fragrance" alt="Fragrance"><br />
    <img src="http://a248.g.akamai.net/7/248/8278/20111004020004/www.sephora.com/assets/global/topNav/nav_bath_off.gif"  id="bathbodyOff" name="bathbody" alt="Bath and Body"><br />
    <img src="http://a248.g.akamai.net/7/248/8278/20111004020004/www.sephora.com/assets/global/topNav/nav_bath_on.gif"  id="bathbodyOn" name="bathbody" alt="Bath and Body"><br />
    <img src="http://a248.g.akamai.net/7/248/8278/20111004020005/www.sephora.com/assets/global/topNav/nav_hair_off.gif"  id="hairOff" name="hair" alt="Hair"><br />
    <img src="http://a248.g.akamai.net/7/248/8278/20111004020005/www.sephora.com/assets/global/topNav/nav_hair_on.gif"  id="hairOn" name="hair" alt="Hair"><br />
    <img src="http://a248.g.akamai.net/7/248/8278/20111004020005/www.sephora.com/assets/global/topNav/nav_tools_off.gif"  id="toolsOff" name="tools" alt="Tools"><br />
    <img src="http://a248.g.akamai.net/7/248/8278/20111004020005/www.sephora.com/assets/global/topNav/nav_tools_on.gif"  id="toolsOn" name="tools" alt="Tools"><br />
    <img src="http://a248.g.akamai.net/7/248/8278/20111223201025/www.sephora.com/assets/global/topNav/nav_men_off.gif"  id="menOff" name="men" alt="Men"><br />

    <img src="http://a248.g.akamai.net/7/248/8278/20111223201025/www.sephora.com/assets/global/topNav/nav_men_on.gif"  id="menOn" name="men" alt="Men"><br />
    <img src="http://a248.g.akamai.net/7/248/8278/20100925012939/www.sephora.com/assets/global/topNav/nav_natural_off.gif"  id="naturalOff" name="natural" alt="Natural & Organic"><br />
    <img src="http://a248.g.akamai.net/7/248/8278/20100925012939/www.sephora.com/assets/global/topNav/nav_natural_on.gif"  id="naturalOn" name="natural" alt="Natural & Organic"><br />
    <img src="http://a248.g.akamai.net/7/248/8278/20111223201025/www.sephora.com/assets/global/topNav/nav_gifts_off.gif" id="giftsOff" name="gifts" alt="Gifts"><br />
    <img src="http://a248.g.akamai.net/7/248/8278/20111223201025/www.sephora.com/assets/global/topNav/nav_gifts_on.gif" id="giftsOn" name="gifts" alt="Gifts"><br />
    <img src="http://a248.g.akamai.net/7/248/8278/20111223201025/www.sephora.com/assets/global/topNav/nav_sephoratv_off.gif" id="sephoratvOff" name="sephoratv" alt="Sephora TV"><br />
    <img src="http://a248.g.akamai.net/7/248/8278/20111223201025/www.sephora.com/assets/global/topNav/nav_sephoratv_on.gif" id="sephoratvOn" name="sephoratv" alt="Sephora TV"><br />
    <img src="http://a248.g.akamai.net/7/248/8278/20111223201025/www.sephora.com/assets/global/topNav/nav_beautyadvice_off.gif" id="beautyadviceOff" name="beautyadvice" alt="Beauty Advice"><br />
    <img src="http://a248.g.akamai.net/7/248/8278/20111223201025/www.sephora.com/assets/global/topNav/nav_beautyadvice_on.gif" id="beautyadviceOn" name="beautyadvice" alt="Beauty Advice"><br />

</div>
<!-- END AKAMAIZED NAV CODE -->

    
<div id="skincareShadow"></div>
<div id="skincareSmear"></div>
<div id="skincareWhite"></div>
<div id="skincareModule">
    <div class="closeSkincare"><a href="#">CLOSE</a></div>
    <div class="heading">
        <img  class="title" src="http://a248.g.akamai.net/7/248/8278/20100324002929/www.sephora.com/assets/go/skincarechallenge/SC_hed.gif" alt="SKINCARE CONSULTATION."/>
        <img class="dek" src="/assets/go/skincarechallenge/dek.gif" alt="Let Sephora Personalize your skincare routine with products that are right for you."/>

    </div>

    <div class="breadcrumb">
        <span class="iconResults"> RESULTS </span>
        <span class="arrow"> <img src="http://a248.g.akamai.net/7/248/8278/20100324002929/www.sephora.com/assets/go/skincarechallenge/arrow.gif" alt="right arrow"/> </span>
        <span class="iconTwo"> 2 </span>

        <span class="arrow"> <img src="http://a248.g.akamai.net/7/248/8278/20100324002929/www.sephora.com/assets/go/skincarechallenge/arrow.gif" alt="right arrow"/> </span>
        <span class="iconOne"> 1 </span>
    </div>

    <div id="quiz" class="clearfix">
        <div id="part3">
            <div class="goToResults">

                <img   src="http://a248.g.akamai.net/7/248/8278/20100324002929/www.sephora.com/assets/go/skincarechallenge/seePreviousResults.gif" alt="see my prevoius results"/>
            </div>
            <div class="retake">
                <img   src="http://a248.g.akamai.net/7/248/8278/20100324002929/www.sephora.com/assets/go/skincarechallenge/startOver.gif" alt="start over"/>
            </div>
        </div>
        <div id="part2">
            <div class="selected">
                <div class=" clearfix">

                    <img src="http://a248.g.akamai.net/7/248/8278/20100324002928/www.sephora.com/assets/go/skincarechallenge/2.gif" alt="2."/>
                    <ul>
                        <label>FACE</label>
                        <li class="sel_0">Minimize pores</li>
                        <li class="sel_1">Clear up blemishes</li>
                        <li class="sel_2">Reduce wrinkles</li>
                        <li class="sel_3">Lift and firm</li>

                        <li class="sel_4">Lighten dark spots</li>
                        <li class="sel_5">Even skin tone</li>
                    
                        <label class="eyes">EYES</label>
                        <li class="sel_6">Brighten dark circles</li>
                        <li class="sel_7">Lift and firm</li>
                        <li class="sel_8">Reduce puffiness</li>

                        <li class="sel_9">Reduce wrinkles</li>
                        <li class="sel_10">All of the above</li>
                    </ul>
                </div>
                <div class="edit"> edit </div>
            </div>
            <div class="problem">

                <div class="question">
                    <img src="http://a248.g.akamai.net/7/248/8278/20100324002928/www.sephora.com/assets/go/skincarechallenge/2Q.gif" alt="2. What are your skin concerns?"/>
                </div>
                <div>
                    <div class="answers clearfix"><img class="intro" src="http://a248.g.akamai.net/7/248/8278/20100628235354/www.sephora.com/assets/go/skincarechallenge/like.gif" alt="I would like to" /><div class="clearfix">
                            <ul class="face">
                                <label>
                                    <img src="http://a248.g.akamai.net/7/248/8278/20100324002929/www.sephora.com/assets/go/skincarechallenge/face.gif" alt="FACE"/>
                                </label>

                                <li><input value="0" type="hidden"/> Minimize pores</li>
                                <li><input value="1" type="hidden"/> Clear up blemishes</li>
                                <li><input value="2" type="hidden"/> Reduce wrinkles</li>
                                <li><input value="3" type="hidden"/> Lift and firm</li>
                                <li><input value="4" type="hidden"/> Lighten dark spots</li>

                                <li><input value="5" type="hidden"/> Even skin tone</li>
                            </ul>
                            <ul class="eyes">
                                <label>
                                    <img src="http://a248.g.akamai.net/7/248/8278/20100324002929/www.sephora.com/assets/go/skincarechallenge/eyes.gif" alt="EYES"/>
                                </label>
                                <li><input value="6" type="hidden"/> Brighten dark circles</li>

                                <li><input value="7" type="hidden"/> Lift and firm</li>
                                <li><input value="8" type="hidden"/> Reduce puffiness</li>
                                <li><input value="9" type="hidden"/> Reduce wrinkles</li>
                                <li><input value="10" type="hidden"/> All of the above</li>
                            </ul>

                        </div>
                    </div>
                </div>
                <div>
                    <input type="image" src="http://a248.g.akamai.net/7/248/8278/20100324002929/www.sephora.com/assets/go/skincarechallenge/getresults.gif" name="getResults" />
                </div>
            </div>
        </div>
        <div id="part1">

            <div class="selected">
                <div class="clearfix">
                    <img src="http://a248.g.akamai.net/7/248/8278/20100324002928/www.sephora.com/assets/go/skincarechallenge/1.gif" alt="1."/>
                    <ul>
                        <li class="sel_0">Normal / <br> Combination </li>
                        <li class="sel_1">Oily</li>
                        <li class="sel_2">Dry</li>

                        <li class="sel_3">Sensitive</li>
                        <li class="sel_4">Aging</li>
                    </ul>
                </div>
                <div class="edit" > edit </div>
            </div>
            <div class="problem">

                <div class="question">
                    <img src="http://a248.g.akamai.net/7/248/8278/20100324002928/www.sephora.com/assets/go/skincarechallenge/1Q.gif" alt="1. What is your skin type?"/>
                </div>
                <div>
                    <div class="answers clearfix" >
                        <img class="intro" src="http://a248.g.akamai.net/7/248/8278/20100324002929/www.sephora.com/assets/go/skincarechallenge/skinTypeIs.gif" alt="My skin type is:"/>
                        <ul class="required">
                            <li><input value="0" type="hidden"/> Normal / Combination</li>

                            <li><input value="1" type="hidden"/> Oily</li>
                            <li><input value="2" type="hidden"/> Dry</li>
                        </ul>
                    </div>
                    <div class="answers clearfix" >
                        <img class="intro" src="http://a248.g.akamai.net/7/248/8278/20100324002929/www.sephora.com/assets/go/skincarechallenge/skinIsAlso.gif" alt="My skin is also:"/>
                        <ul class="optional">

                            <li><input value="3" type="hidden"/> Sensitive</li>
                            <li><input value="4" type="hidden"/> Aging</li>
                        </ul>
                    </div>
                </div>
                <div>
                    <div class="error"> choose 1 skin type </div>

                    <input type="image" src="http://a248.g.akamai.net/7/248/8278/20100324002929/www.sephora.com/assets/go/skincarechallenge/next.gif" name="next" width="53px" height="22px"/>
                </div>
            </div>
        </div>

    </div>

    <div id="acne">
        <a href="/browse/section.jhtml?categoryId=C8882">
            <img src="http://a248.g.akamai.net/7/248/8278/20100324002929/www.sephora.com/assets/go/skincarechallenge/acne.gif" alt="Need acne help? If acne is your main concern visit our Ance/Blemish Solutions category."/>

        </a>
    </div>
    <div class="tooltip"></div>

</div>


<script type="text/javascript">
    if (location.protocol.indexOf('http:') != -1){
        _qoptions={qacct:"p-efJbv8XhssAmI",labels:""};
        document.write('<scr' + 'ipt type="text/javascript" src="http://edge.quantserve.com/quant.js"><\/scr' + 'ipt>');
    }else{
        _qoptions={qacct:"p-efJbv8XhssAmI",labels:""};
        document.write('<scr' + 'ipt type="text/javascript" src="https://secure.quantserve.com/quant.js"><\/scr' + 'ipt>');
    }
</script>


<script type="text/javascript"> 
if (jQuery) { jQuery(document).ready(function() { if(typeof location.protocol === 'string') { jQuery.getScript(location.protocol + '//tags.mediaforge.com/js/400' + ((typeof window.CI_ItemID === 'string') ? ('/?prodID=' + window.CI_ItemID) : ((typeof bidOrId !== 'undefined' && typeof bidOrTot !== 'undefined') ? ('/?orderNumber=' + bidOrId + '&price=' + bidOrTot) : (((typeof window.categoryID === 'string') && (window.categoryID !== 'none'))? ('/?catID=' + window.categoryID) : '')))); } }); }
</script>
</body>

ddd
<div id="mojoNotification" style="background-color: rgb(252, 238, 170); background-position: center bottom; height: 51px; position: absolute; width: 100%; left: 0px; top: -51px; right: 0px; ">	
</div>


<div style="background:red; height:51px; width:800px;">
	
</div>

</html>


