<link rel="stylesheet" type="text/css" href="/chichi/public/css/tabs.css" />
<link rel="stylesheet" type="text/css" href="/chichi/public/css/style.css" />
<link rel="stylesheet" type="text/css" href="/chichi/public/css/view.css" />
<link rel="stylesheet" type="text/css" href="/chichi/public/css/gallery.css" />
<script type="text/javascript" src="/chichi/public/js/jquery.js"></script>
<script type="text/javascript" src="/chichi/public/js/tabs.js"> </script>
<script type="text/javascript" src="/chichi/public/js/view.js"> </script>
<script type="text/javascript" src="/chichi/public/js/gallery.js"> </script>

<script type="text/javascript">
$(document).ready(function(){
	var myImages=new Array( "http://i.walmartimages.com/i/p/00/89/05/98/01/0089059801010_100X100.jpg","http://images.bestbuy.com/BestBuy_US/images/products/3109/3109302_sb.jpg");
	$('a').click(function() {
		  	var id = $("img:first").attr("id");
	 		var str = id.split("_");
  			if(this.id == "prev"){
	 			var current = myImages[parseInt(str[3])-1];
	 			var current_id =  parseInt(str[3])-1;
	 			$("img:first").attr("id", "current_prod_image_" + current_id); 	
	 			$("img:first").attr("src", current); 				
  			}
  			else if(this.id == "next"){
	 			var current = myImages[parseInt(str[3])+1];
	 			var current_id =  parseInt(str[3])+1;
	 			$("img:first").attr("id", "current_prod_image_" + current_id); 	
	 			$("img:first").attr("src", current); 

  			}
	});
});
</script> 



<p></p>



<img src="http://i.walmartimages.com/i/p/00/89/05/98/01/0089059801010_100X100.jpg" id="current_prod_image_0" width="150" height="150" />



<br />
<br />
<br />
<a id="prev" > Prev</a>
<a id="next" > Next</a>
