
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>Easy Slider jQuery Plugin Demo</title>
	<meta http-equiv="content-type" content="text/html;charset=UTF-8" />    
	<script type="text/javascript" src="/chichi/public/js/jquery.js"></script>
	<script type="text/javascript" src="/chichi/public/js/product.js"> </script>
</head>
<body>
<form action="/chichi/public/index/share" method="post">

	<?php 

		if(isset($this->data)){
			echo "<label>Product Name: </label>";
			echo "<label>". $this->data[0] ."<label>";
			echo "<input type='hidden' value='".$this->data[0]."' name='product_title' />";
			echo "<br />";
			echo "<label>Product Description:</label>";
			echo "<label>". $this->data[2] ."<label>";
			echo "<input type='hidden' value='".$this->data[2]."' name='product_description' />";
			echo "<br />";
			echo "<label>Product Price:</label>";
			echo "<input type='hidden' value='".$this->data[1]."' name='product_price' />";
			echo "<label>". $this->data[1] ."<label>";
			echo "<ul id='products_images'>";
			if(is_array($this->data[3])){
				foreach($this->data[3] as $key => $value){
					echo '<input type="hidden" value="'.$value.'"> ';		
				}
			}
			echo '<img src="" id="current" />';	
			echo "</ul>";		
		}
	?>
	
	<input type="submit" />
</form>
<br />
	
	<a id="prev"> Prev</a>
	<a id="next" id="next"> Next</a>
	
</body>
</html>