<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>Easy Slider jQuery Plugin Demo</title>
	<meta http-equiv="content-type" content="text/html;charset=UTF-8" />    
	<script type="text/javascript" src="/chichi/public/js/product.js"> </script>
</head>
<body>
<form action="/chichi/public/index/share" method="post">
<table height="50" width="100%" border="0">
	<tr>
		<td style="text-align: right;"><h4>Product Name:</h4></td>
		<td><?php echo $this->data[0]; ?></td>	
	</tr>
	<tr>
		<td style="text-align: right;"><h4>Product Description:</h4></td>
		<td><?php echo $this->data[2]; ?></td>	
	</tr>
	<tr>
		<td style="text-align: right;"><h4>Product Price: </h4></td>
		<td><?php echo $this->data[1]; ?></td>
	</tr>	
	<tr>
		<td style="text-align: right;"><h4>Product Image: </h4></td>
		<td><img src="<?php echo $this->data[3][0]; ?>" width="50" height="50" /></td>
	</tr>	
	<tr height="10">	
	</tr>
	<tr>
		<td></td>
		<td><input type="submit" style="background-image:url('/chichi/public/images/button-submit.jpg'); border:0; width:92px; height:16px; cursor:pointer;" value="" /></td>
	</tr>
</table>
<?php
			echo "<input type='hidden' value='".$this->data[0]."' name='product_title' />";
			echo "<input type='hidden' value='".$this->data[2]."' name='product_description' />";
			echo "<input type='hidden' value='".$this->data[1]."' name='product_price' />";
?>
</form>
<br />
	
</body>
</html>