<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Creating a Facebook-like Registration Form with jQuery</title>
<link rel="stylesheet" type="text/css" href="/chichi/public/css/tabs.css" />
<link rel="stylesheet" type="text/css" href="/chichi/public/css/style.css" />
<script type="text/javascript" src="/chichi/public/js/jquery.js"></script>
<script type="text/javascript" src="/chichi/public/js/tabs.js"> </script>
</head>
<body>
	<div id="page-wrap">			
		<div id="zone-bar">
			<ul>
				<li>
					<a href="#"><span>
						Technology &nbsp;
						<em class="opener-technology">
							<img src="/chichi/public/images/zonebar-downarrow.png" alt="dropdown" />
						</em>
					</span></a>
					<ul class="technologysublist">
						<li><a href="#">Apple</a></li>
						<li><a href="#">Design</a></li>
						<li><a href="#">Gadgets</a></li>
						<li><a href="#">Hardware</a></li>
						<li><a href="#">Industry News</a></li>
						<li><a href="#">Linux/Unix</a></li>
						<li><a href="#">Microsoft</a></li>
						<li><a href="#">Mods</a></li>
						<li><a href="#">Programming</a></li>
						<li><a href="#">Security</a></li>
						<li><a href="#">Software</a></li>
					</ul>
				</li>
				<li>
					<a href="#"><span>
						World &amp; Business &nbsp;
						<em class="opener-world">
							<img src="/chichi/public/images/zonebar-downarrow.png" alt="dropdown" />
						</em>
					</span></a>
					<ul class="worldsublist">
						<li><a href="#">Business &amp; Finance</a></li>
						<li><a href="#">World News</a></li>
						<li><a href="#">Political News</a></li>
						<li><a href="#">Political Opinion</a></li>
						<li><a href="#">2008 Elections</a></li>
					</ul>
				</li>
				<li>
					<a href="#"><span>
						Science &nbsp;
						<em class="opener-science">
							<img src="/chichi/public/images/zonebar-downarrow.png" alt="dropdown" />
						</em>
					</span></a>
					<ul class="sciencesublist">
						<li><a href="#">Enviornment</a></li>
						<li><a href="#">General Sciences</a></li>
						<li><a href="#">Space</a></li>
					</ul>
				</li>
				<li>
					<a href="#"><span>
						Gaming &nbsp;
						<em class="opener-gaming">
							<img src="/chichi/public/images/zonebar-downarrow.png" alt="dropdown" />
						</em>
					</span></a>
					<ul class="gamingsublist">
						<li><a href="#">Industry News</a></li>
						<li><a href="#">PC Games</a></li>
						<li><a href="#">Playable Web Games</a></li>
						<li><a href="#">Nintendo</a></li>
						<li><a href="#">PlayStation</a></li>
						<li><a href="#">XBox</a></li>
					</ul>
				</li>
				<li>
					<a href="#"><span>
						Lifestyle &nbsp;
						<em class="opener-lifestyle">
							<img src="/chichi/public/images/zonebar-downarrow.png" alt="dropdown" />
						</em>
					</span></a>
					<ul class="lifestylesublist">
						<li><a href="#">Arts &amp; Culture</a></li>
						<li><a href="#">Autos</a></li>
						<li><a href="#">Educational</a></li>
						<li><a href="#">Food &amp; Drink</a></li>
						<li><a href="#">Health</a></li>
						<li><a href="#">Travel &amp; Places</a></li>
					</ul>
				</li>
				<li>
					<a href="#"><span>
						Entertainment &nbsp;
						<em class="opener-entertainment">
							<img src="/chichi/public/images/zonebar-downarrow.png" alt="dropdown" />
						</em>
					</span></a>
					<ul class="entertainmentsublist">
						<li><a href="#">Celebrity</a></li>
						<li><a href="#">Movies</a></li>
						<li><a href="#">Music</a></li>
						<li><a href="#">Television</a></li>
						<li><a href="#">Comics &amp; Animation</a></li>
					</ul>
				</li>
				<li>
					<a href="#"><span>
						Sports &nbsp;
						<em class="opener-sports">
							<img src="/chichi/public/images/zonebar-downarrow.png" alt="dropdown" />
						</em>
					</span></a>
					<ul class="sportssublist">
						<li><a href="#">Baseball</a></li>
						<li><a href="#">Basketball</a></li>
						<li><a href="#">Extreme</a></li>
						<li><a href="#">Football</a></li>
						<li><a href="#">Golf</a></li>
						<li><a href="#">Hockey</a></li>
						<li><a href="#">Motorsport</a></li>
						<li><a href="#">Soccer</a></li>
						<li><a href="#">Tennis</a></li>
						<li><a href="#">Other Sports</a></li>
					</ul>
				</li>
				<li>
					<input type="text" id="searc_friends" style="background: white url(http://a.xnimg.cn/imgpro/bg/cs_navtop.png?timestamp=091126) no-repeat left -175px;
border: 1px solid #315091;
float: left;
height: 15px;
margin: 0;
padding: 3px 4px;
width: 149px;
margin-top: -3px;" />
					<ul class="offbeatsublist">
						<li><a href="#">Comedy</a></li>
						<li><a href="#">Odd Stuff</a></li>
						<li><a href="#">People</a></li>
						<li><a href="#">Pets &amp; Animals</a></li>
					</ul>
				</li>
				
		
			</ul>			
		</div>




	
	<div id="container" style=" width:1000px; margin-top: 62.5px; float: left; ">	
			<div style="overflow:auto; height:25px;" id="message_box">	
				<div style="float: left; margin-left:2.5px; font-size:1.7em;"><?php echo $this->current_user.": ";  ?> </div>	
			<!--	<div style="float: left; margin-left:5px;" id="status_msg_box"><?php foreach($this->latest as $key => $value){echo $value;}?></div>	-->
			</div>
		<ul class="menu">
			<li id="news" class="active">News</li>
			<li id="tutorials">Profile</li>
			<li id="links">Links</li>
		</ul>
		<span class="clear"></span>
		<div class="content news">
		
		</div>		
		<div class="content tutorials">
			<div id="product_scrapper">
									<h1>Share Your Purchases</h1>
				<div id="left">
					<form action="/chichi/public/index/product" method="post">
							<input type="text" id="scrapper" name="scrapper" size="20" />
							<br />
							<input type="submit" id="continue" value="" />	
					</form>			
					</div>
					<div id="right">
							<ul>
								 <li><img src="/chichi/public/images/bullet.png" />It's totall free</li>
								 <li><img src="/chichi/public/images/bullet.png" />Let your friends what you have purchased</li>
								 <li><img src="/chichi/public/images/bullet.png" />What is your favoriate gift</li>
							</ul>
					</div>
					
			</div>
			

		
		</div>
		<div class="content links">
			<h1>You may visit</h1>
			<ul>
				<li><img src="css/images/bullet.gif" alt="-" /> <a href="http://www.plusmusica.com">www.plusmusica.com</a> - Online jukebox!</li>
				<li><img src="css/images/bullet.gif" alt="-" /> <a href="http://www.cokidoo.com">www.cokidoo.com</a> - Awesome startup! :)</li>
				<li><img src="css/images/bullet.gif" alt="-" /> <a href="http://www.cokidoo.com">www.pixelartgames.com</a> - Do you want pixel art games? ;)</li>
				<li><img src="css/images/bullet.gif" alt="-" /> <a href="http://www.dmsconsulting.es">www.dmsconsulting.es</a> - Great guys</li>
			<ul>
		</div>
	</div>
	
	




</body>
</html>
