<?php

function get_time_difference( $start)
{
    $uts['start']      =    $start;
    $uts['end']        =    strtotime("now");
    if( $uts['start']!==-1 && $uts['end']!==-1 )
    {
        if( $uts['end'] >= $uts['start'] )
        {
            $diff    =    $uts['end'] - $uts['start'];
            if( $days=intval((floor($diff/86400))) )
                $diff = $diff % 86400;
            if( $hours=intval((floor($diff/3600))) )
                $diff = $diff % 3600;
            if( $minutes=intval((floor($diff/60))) )
                $diff = $diff % 60;
            $diff = intval( $diff );            
            return( array('days'=>$days, 'hours'=>$hours, 'minutes'=>$minutes, 'seconds'=>$diff) );
        }
        else
        {
            trigger_error( "Ending date/time is earlier than the start date/time", E_USER_WARNING );
        }
    }
    else
    {
        trigger_error( "Invalid date/time data detected", E_USER_WARNING );
    }
    return( false );
}

?>


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Creating a Facebook-like Registration Form with jQuery</title>
<link rel="stylesheet" type="text/css" href="/chichi/public/css/tabs.css" />
<link rel="stylesheet" type="text/css" href="/chichi/public/css/style.css" />
<link rel="stylesheet" type="text/css" href="/chichi/public/css/view.css" />
<script type="text/javascript" src="/chichi/public/js/jquery.js"></script>
<script type="text/javascript" src="/chichi/public/js/tabs.js"> </script>
<script type="text/javascript" src="/chichi/public/js/view.js"> </script>
<script type="text/javascript" src="/chichi/public/js/slider.js"> </script>


<style type="text/css">
.menu_list {
	magrin-top:75px;	
	width: 160px;
}
.menu_head {
	padding: 5px 10px;
	cursor: pointer;
	position: relative;
	margin:1px;
    font-weight:bold;
    background: #D2E0EA url(left.png) center right no-repeat;
}
.menu_body {
	display:none;
}
.menu_body a{
  display:block;
  color:#006699;
  background-color:#EFEFEF;
  padding-left:10px;
  font-weight:bold;
  text-decoration:none;
}
.menu_body a:hover{
  color: #000000;
  text-decoration:underline;
  }
  
  #gallery {
    padding: 30px;
    background: #e1eef5;
  }
  #descriptions {
    position: relative;
    height: 50px;
    background: #EEE;
    margin-top: 10px;
    width: 340px;
    padding: 10px;
    overflow: hidden;
  }
    #descriptions .ad-image-description {
      position: absolute;
    }
      #descriptions .ad-image-description .ad-description-title {
        display: block;
      }
</style>

</head>
<body>
	<input type="hidden" value="<?php echo $this->current_user; ?>" id="current_user" />
	<div id="page-wrap">			
		<div id="zone-bar">
			<ul>
				<li>
					<a href="#"><span>
						Technology &nbsp;
						<em class="opener-technology">
							<img src="/chichi/public/images/zonebar-downarrow.png" alt="dropdown" />
						</em>
					</span></a>
					<ul class="technologysublist">
						<li><a href="#">Apple</a></li>
						<li><a href="#">Design</a></li>
						<li><a href="#">Gadgets</a></li>
						<li><a href="#">Hardware</a></li>
						<li><a href="#">Industry News</a></li>
						<li><a href="#">Linux/Unix</a></li>
						<li><a href="#">Microsoft</a></li>
						<li><a href="#">Mods</a></li>
						<li><a href="#">Programming</a></li>
						<li><a href="#">Security</a></li>
						<li><a href="#">Software</a></li>
					</ul>
				</li>
				<li>
					<a href="#"><span>
						World &amp; Business &nbsp;
						<em class="opener-world">
							<img src="/chichi/public/images/zonebar-downarrow.png" alt="dropdown" />
						</em>
					</span></a>
					<ul class="worldsublist">
						<li><a href="#">Business &amp; Finance</a></li>
						<li><a href="#">World News</a></li>
						<li><a href="#">Political News</a></li>
						<li><a href="#">Political Opinion</a></li>
						<li><a href="#">2008 Elections</a></li>
					</ul>
				</li>
				<li>
					<a href="#"><span>
						Science &nbsp;
						<em class="opener-science">
							<img src="/chichi/public/images/zonebar-downarrow.png" alt="dropdown" />
						</em>
					</span></a>
					<ul class="sciencesublist">
						<li><a href="#">Enviornment</a></li>
						<li><a href="#">General Sciences</a></li>
						<li><a href="#">Space</a></li>
					</ul>
				</li>
				<li>
					<a href="#"><span>
						Gaming &nbsp;
						<em class="opener-gaming">
							<img src="/chichi/public/images/zonebar-downarrow.png" alt="dropdown" />
						</em>
					</span></a>
					<ul class="gamingsublist">
						<li><a href="#">Industry News</a></li>
						<li><a href="#">PC Games</a></li>
						<li><a href="#">Playable Web Games</a></li>
						<li><a href="#">Nintendo</a></li>
						<li><a href="#">PlayStation</a></li>
						<li><a href="#">XBox</a></li>
					</ul>
				</li>
				<li>
					<a href="#"><span>
						Lifestyle &nbsp;
						<em class="opener-lifestyle">
							<img src="/chichi/public/images/zonebar-downarrow.png" alt="dropdown" />
						</em>
					</span></a>
					<ul class="lifestylesublist">
						<li><a href="#">Arts &amp; Culture</a></li>
						<li><a href="#">Autos</a></li>
						<li><a href="#">Educational</a></li>
						<li><a href="#">Food &amp; Drink</a></li>
						<li><a href="#">Health</a></li>
						<li><a href="#">Travel &amp; Places</a></li>
					</ul>
				</li>
				<li>
					<a href="#"><span>
						Entertainment &nbsp;
						<em class="opener-entertainment">
							<img src="/chichi/public/images/zonebar-downarrow.png" alt="dropdown" />
						</em>
					</span></a>
					<ul class="entertainmentsublist">
						<li><a href="#">Celebrity</a></li>
						<li><a href="#">Movies</a></li>
						<li><a href="#">Music</a></li>
						<li><a href="#">Television</a></li>
						<li><a href="#">Comics &amp; Animation</a></li>
					</ul>
				</li>
				<li>
					<a href="#"><span>
						Sports &nbsp;
						<em class="opener-sports">
							<img src="/chichi/public/images/zonebar-downarrow.png" alt="dropdown" />
						</em>
					</span></a>
					<ul class="sportssublist">
						<li><a href="#">Baseball</a></li>
						<li><a href="#">Basketball</a></li>
						<li><a href="#">Extreme</a></li>
						<li><a href="#">Football</a></li>
						<li><a href="#">Golf</a></li>
						<li><a href="#">Hockey</a></li>
						<li><a href="#">Motorsport</a></li>
						<li><a href="#">Soccer</a></li>
						<li><a href="#">Tennis</a></li>
						<li><a href="#">Other Sports</a></li>
					</ul>
				</li>
				<li>
					<input type="text" id="searc_friends" style="background: white url(http://a.xnimg.cn/imgpro/bg/cs_navtop.png?timestamp=091126) no-repeat left -175px;
border: 1px solid #315091;
float: left;
height: 15px;
margin: 0;
padding: 3px 4px;
width: 149px;
margin-top: -3px;" />
					<ul class="offbeatsublist">
						<li><a href="#">Comedy</a></li>
						<li><a href="#">Odd Stuff</a></li>
						<li><a href="#">People</a></li>
						<li><a href="#">Pets &amp; Animals</a></li>
					</ul>
				</li>
				
		
			</ul>			
		</div>




	
	<div id="container" style=" width:1000px; margin-top: 62.5px; float: left; ">	
			<div style="overflow:auto; height:25px;" id="message_box">	
				<div style="float: left; margin-left:2.5px; font-size:1.7em;"><?php echo $this->current_user.": ";  ?> </div>	
			<!--	<div style="float: left; margin-left:5px;" id="status_msg_box"><?php foreach($this->latest as $key => $value){echo $value;}?></div>	-->
			</div>
		<ul class="menu">
			<li id="news" class="active">News</li>
			<li id="tutorials">Profile</li>
			<li id="links">Links</li>
		</ul>
		<span class="clear"></span>
		<div class="content news">
			<div id="publisher">
				<textarea id="message" value="What are you doing now?">What are you doing now?</textarea>
				<input type="submit"  id="msg_submit" value="Submit" />
				<input type="hidden" value="<?php echo $this->current_user?>" id="current"  />
			</div>
	
			<div style="overflow:auto;" id="db_message_box">
					
						
						<?php 
							foreach($this->data as $key => $value){
										echo '<div id="leftside" style="float:left;">
								<img src="http://hdn.xnimg.cn/photos/hdn421/20111205/1525/h_tiny_IM0v_6f9b00029d702f76.jpg" width="50" height="50">
							</div>';
									echo '<div id="rightside" style="margin-left: 55px;">';
							
										echo "<span style='color:#005EAC'>";
										echo $value["user"].": ";
										echo "</span>";
										echo $value["message"];
										if(!empty($value["comments"])){
											?>
										<div id="comments<?php echo "_".$value["M_id"];?>">												
											<?php
											foreach($value["comments"] as $key => $val){
												echo "<div id='comment'>";
												echo $val["sent_user"].": ";
												echo '<span style="color:black">';
												echo $val["comment"];
												echo '</span>';													
												echo "<br />";
												echo "</div>";
												
											}
										echo '</div>';
										}	
											//	echo $val;
									?>	
										<textarea id="<?php echo "tweet_".$value["M_id"]; ?>" rows="2" placeholder="Leave comments"></textarea>
												<input type="submit"  id="sub_com" value="Submit"  />
												<br />
									</div>																			
									<?php
							}
						?>
			</div>
		</div>		
		<div class="content tutorials">
			<div id="product_scrapper">
									<h1>Share Your Purchases</h1>
				<div id="left">
					<form action="/chichi/public/index/product" method="post">
							<input type="text" id="scrapper" name="scrapper" size="20" />
							<br />
							<input type="submit" id="continue" value="" />	
					</form>			
					</div>
					<div id="right">
							<ul>
								 <li><img src="/chichi/public/images/bullet.png" />It's totall free</li>
								 <li><img src="/chichi/public/images/bullet.png" />Let your friends what you have purchased</li>
								 <li><img src="/chichi/public/images/bullet.png" />What is your favoriate gift</li>
							</ul>
					</div>
					
			</div>
			

		
		</div>
		<div class="content links">
			<h1>You may visit</h1>
			<ul>
				<li><img src="css/images/bullet.gif" alt="-" /> <a href="http://www.plusmusica.com">www.plusmusica.com</a> - Online jukebox!</li>
				<li><img src="css/images/bullet.gif" alt="-" /> <a href="http://www.cokidoo.com">www.cokidoo.com</a> - Awesome startup! :)</li>
				<li><img src="css/images/bullet.gif" alt="-" /> <a href="http://www.cokidoo.com">www.pixelartgames.com</a> - Do you want pixel art games? ;)</li>
				<li><img src="css/images/bullet.gif" alt="-" /> <a href="http://www.dmsconsulting.es">www.dmsconsulting.es</a> - Great guys</li>
			<ul>
		</div>
	</div>
	
	
<div style="width: 200px; margin-top: 100px; margin-left: 1060px;"> <!--This is the second division of right-->
  <div class="menu_list" id="secondpane" style="width: 200px;"> <!--Code for menu starts here-->
		<p class="menu_head">Header-1</p>
		<div class="menu_body">
		<a href="#">Link-1</a>
         <a href="#">Link-2</a>
         <a href="#">Link-3</a>	
		</div>
		<p class="menu_head">Header-2</p>
		<div class="menu_body">
			<a href="#">Link-1</a>
         <a href="#">Link-2</a>
         <a href="#">Link-3</a>	
		</div>
		<p class="menu_head">Header-3</p>
		<div class="menu_body">
          <a href="#">Link-1</a>
         <a href="#">Link-2</a>
         <a href="#">Link-3</a>			
       </div>
  </div>      <!--Code for menu ends here-->
</div>


<div id="friends">
	<div id="header">
		My Friends
	</div>
	<div id="section">		
			<div id="left_side">
				<img src="/chichi/public/index/image?id=<?php echo $this->friends[0]->id; ?>" width="50" height="50"/><br />											
			</div>
			<div id="right_side">
						<img src="/chichi/public/index/image?id=<?php echo $this->friends[1]->id; ?>" width="50" height="50"/>
			</div>
			<div id="left_side" style="margin-top:10px;">
						<img  src="/chichi/public/index/image?id=<?php echo $this->friends[0]->id; ?>"width="50" height="50"/>
			</div>
			<div id="right_side" style="margin-top:10px;">
						<img  src="/chichi/public/index/image?id=<?php echo $this->friends[1]->id; ?>" width="50" height="50"/>
			</div>
	</div>
</div>
</body>
</html>
