
<html>
<head>
<link rel="stylesheet" href="/chichi/public/css/global.css" />
<script type="text/javascript" src="/chichi/public/js/prototype.js">  </script>
<script type="text/javascript">
	   Event.observe(window, 'load', function(){
            Element.observe('register', 'click', function(){ 			
					$(down_overlay).show();		
					$(reg_form).show();	
            	})
			Element.observe('close_reg', 'click', function(){ 			
					$(down_overlay).hide();		
					$(reg_form).hide();	
            	})           	           
            });	
</script>
</head>
<body>
<div id="down_overlay" style="display:block; position: absolute;"></div> 
<div id="reg_form" style="display: block; ">
<a id="close_reg" style="cursor: pointer;">	<img src="/chichi/public/images/close.png" width="20" height="20"  /> </a>
<?php
	if(isset($this->error)){
		echo "<h2 class='incorr_pass'>";	
		echo $this->error;
		echo "</h2>";
	}
	echo $this->form;
?>
</div>

	<div id="body_content">
		<div id="login_box">
			<table cellpadding="3" cellspacing="0"><tr><td>Email:</td></tr> <tr><td> <input type="text" /></td></tr> <tr> <td> Password:</td></tr> <tr><td><input type="text" /> </td></tr> </table>
			<div class="sub" style="left: 100px;"> <input type="submit" style="margin-left:45px; position: relative; left: 25px; bottom: 5px;" value="Submit"  /> </div>
			<div style="margin-left:55px; margin-top:10px; position: relative; bottom: 5px; "><button id="register">New User? </button> </div>
		</div>
		<div id="back_image">
			<img src="/chichi/public/images/1fa9f30a8829e3823bc76398.jpg" height="500" />
		</div>
	</div>


