<link rel="stylesheet" type="text/css" href="/chichi/public/css/tabs.css" />
<link rel="stylesheet" type="text/css" href="/chichi/public/css/style.css" />
<script type="text/javascript" src="/chichi/public/js/jquery.js"></script>
<script type="text/javascript" src="/chichi/public/js/tabs.js"> </script>

<form method="post" action="/chichi/public/index/test">
	<input type="text" name="product" />
	<input type="submit" />
</form>


<form action="/chichi/public/index/test"  method="post">
<select name="type"> <option value="fullname">Fullname </option> <option value="email">Email </option></select>
<input type="text" name="friend"  />
<input type="submit" />
</form>



<form action="#">
<input type="text" id="tweet_1"  />
<input type="submit" id="sub_com" />
</form>

