<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Creating a Facebook-like Registration Form with jQuery</title>
<link rel="stylesheet" type="text/css" href="/chichi/public/css/tabs.css" />
<link rel="stylesheet" type="text/css" href="/chichi/public/css/style.css" />
<script type="text/javascript" src="/chichi/public/js/jquery.js"></script>
<script type="text/javascript" src="/chichi/public/js/tabs.js"> </script>
</head>
<body>
	<div id="page-wrap">			
		<div id="zone-bar">
			<ul>
				<li>
					<a href="#">
						<span>Technology &nbsp;
							<em class="opener-technology">
								<img src="/chichi/public/images/zonebar-downarrow.png" alt="dropdown" />
							</em>
						</span>
					</a>
					<ul class="technologysublist">
						<li><a href="#">Apple</a></li>
						<li><a href="#">Design</a></li>
						<li><a href="#">Gadgets</a></li>
						<li><a href="#">Hardware</a></li>
						<li><a href="#">Industry News</a></li>
						<li><a href="#">Linux/Unix</a></li>
						<li><a href="#">Microsoft</a></li>
						<li><a href="#">Mods</a></li>
						<li><a href="#">Programming</a></li>
						<li><a href="#">Security</a></li>
						<li><a href="#">Software</a></li>
					</ul>
				</li>
				<li>
					<a href="#"><span>
						World &amp; Business &nbsp;
						<em class="opener-world">
							<img src="/chichi/public/images/zonebar-downarrow.png" alt="dropdown" />
						</em>
					</span></a>
					<ul class="worldsublist">
						<li><a href="#">Business &amp; Finance</a></li>
						<li><a href="#">World News</a></li>
						<li><a href="#">Political News</a></li>
						<li><a href="#">Political Opinion</a></li>
						<li><a href="#">2008 Elections</a></li>
					</ul>
				</li>
				<li>
					<a href="#"><span>
						Science &nbsp;
						<em class="opener-science">
							<img src="/chichi/public/images/zonebar-downarrow.png" alt="dropdown" />
						</em>
					</span></a>
					<ul class="sciencesublist">
						<li><a href="#">Enviornment</a></li>
						<li><a href="#">General Sciences</a></li>
						<li><a href="#">Space</a></li>
					</ul>
				</li>
				<li>
					<a href="#"><span>
						Gaming &nbsp;
						<em class="opener-gaming">
							<img src="/chichi/public/images/zonebar-downarrow.png" alt="dropdown" />
						</em>
					</span></a>
					<ul class="gamingsublist">
						<li><a href="#">Industry News</a></li>
						<li><a href="#">PC Games</a></li>
						<li><a href="#">Playable Web Games</a></li>
						<li><a href="#">Nintendo</a></li>
						<li><a href="#">PlayStation</a></li>
						<li><a href="#">XBox</a></li>
					</ul>
				</li>
				<li>
					<a href="#"><span>
						Lifestyle &nbsp;
						<em class="opener-lifestyle">
							<img src="/chichi/public/images/zonebar-downarrow.png" alt="dropdown" />
						</em>
					</span></a>
					<ul class="lifestylesublist">
						<li><a href="#">Arts &amp; Culture</a></li>
						<li><a href="#">Autos</a></li>
						<li><a href="#">Educational</a></li>
						<li><a href="#">Food &amp; Drink</a></li>
						<li><a href="#">Health</a></li>
						<li><a href="#">Travel &amp; Places</a></li>
					</ul>
				</li>
				<li>
					<a href="#"><span>
						Entertainment &nbsp;
						<em class="opener-entertainment">
							<img src="/chichi/public/images/zonebar-downarrow.png" alt="dropdown" />
						</em>
					</span></a>
					<ul class="entertainmentsublist">
						<li><a href="#">Celebrity</a></li>
						<li><a href="#">Movies</a></li>
						<li><a href="#">Music</a></li>
						<li><a href="#">Television</a></li>
						<li><a href="#">Comics &amp; Animation</a></li>
					</ul>
				</li>
				<li>
					<a href="#"><span>
						Sports &nbsp;
						<em class="opener-sports">
							<img src="/chichi/public/images/zonebar-downarrow.png" alt="dropdown" />
						</em>
					</span></a>
					<ul class="sportssublist">
						<li><a href="#">Baseball</a></li>
						<li><a href="#">Basketball</a></li>
						<li><a href="#">Extreme</a></li>
						<li><a href="#">Football</a></li>
						<li><a href="#">Golf</a></li>
						<li><a href="#">Hockey</a></li>
						<li><a href="#">Motorsport</a></li>
						<li><a href="#">Soccer</a></li>
						<li><a href="#">Tennis</a></li>
						<li><a href="#">Other Sports</a></li>
					</ul>
				</li>
				<li>
				<ul class="offbeatsublist">
						<li><a href="#">Comedy</a></li>
						<li><a href="#">Odd Stuff</a></li>
						<li><a href="#">People</a></li>
						<li><a href="#">Pets &amp; Animals</a></li>
					</ul>
				</li>
			</ul>			
		</div>	
		<?php echo $this->layout()->content ?>
</body>
</html>
